macOS: add methods to setup transparent titlebar with custom height
JetBrains/JetBrainsRuntime pull request #100
Opened 2021-12-06 10:27 UTC by greg-kargin

Hi! 

In Fleet, we have a custom-painted title bar on macOS with non-default height. We had this logic implemented in Skiko, but recently we needed to add additional hit tests, so double click on buttons doesn't maximize the window. And we decided to move that to JBR to be consistent with our custom title bar implementation on Windows, which also uses JBR custom decorations and hit tests.

2021-12-10 14:50 UTC, avu requested changes

2021-12-14 00:07 UTC, greg-kargin commented on src/java.desktop/macosx/classes/sun/lwawt/macosx/CPlatformWindow.java
> +    private static native void nativeTransparentTitleBarWithCustomHeight(long nsWindowPtr, float height);
Hi! I've added the property, so it's easier to use in IJ later. But, if I understood everything correctly in Fleet we won't be able to use that as we are running on bare AWT, so on the Fleet side I will keep jni call.

2021-12-14 00:07 UTC, greg-kargin commented on src/java.desktop/macosx/native/libawt_lwawt/awt/AWTWindow.h
> +    BOOL _titlebarDisabled;
removed this one

2021-12-14 00:09 UTC, greg-kargin commented on src/java.desktop/macosx/native/libawt_lwawt/awt/AWTWindow.m
> +     * The view hierarchy looks as follows:
I will need to phone a friend for this one 😅
cc @manu-unter

2021-12-14 00:11 UTC, greg-kargin commented on src/java.desktop/macosx/native/libawt_lwawt/awt/AWTWindow.m
> +    BOOL runningAtLeastBigSur = @available(macOS 11.0, *);
yeah, it compiled with `--disable-warnings-as-errors`, should be fixed now.

2021-12-14 09:02 UTC, manu-unter commented on src/java.desktop/macosx/native/libawt_lwawt/awt/AWTWindow.m
> +     * The view hierarchy looks as follows:
Hey! The hierarchy is there natively already. It's responsible for drawing the controls and the title, plus any visual effects such as slight transparency and blur (the Big Sur glass effect)

Most of these views are hidden in our specific window configuration in fleet, and they wouldn't be necessary to get a draggable header either. I decided to not just delete them though so it is possible to restore the initial state more easily if ever necessary.

We achieve the custom header height then by deactivating the default constraints on them and setting up custom ones. Reverting is then just the other way around: removing custom constraints and reactivating the default ones.

Does that answer your question?

2021-12-16 19:26 UTC, avu commented on src/java.desktop/macosx/native/libawt_lwawt/awt/AWTWindow.m
> +    BOOL runningAtLeastBigSur = [[NSProcessInfo processInfo] operatingSystemVersion].majorVersion >= 11;
I would extend and use our existing mechanism here. See src/java.desktop/macosx/native/libawt_lwawt/awt/LWCToolkit.h

The following lines can be added here to cover BigSur

#ifndef kCFCoreFoundationVersionNumber10_15_Max
#define kCFCoreFoundationVersionNumber10_15_Max 1699
#endif

#ifndef IS_OSX_GT10_15
#define IS_OSX_GT10_15 (floor(kCFCoreFoundationVersionNumber) > \
kCFCoreFoundationVersionNumber10_15_Max)
#endif

2021-12-16 19:33 UTC, avu commented
Could you add a regression test here, you can use the following as a template: test/jdk/java/awt/Window/WindowAppearanceTest/WindowAppearanceTest.java as a template. The JB regression tests are located here test/jdk/jb/

2021-12-16 19:36 UTC, avu commented on src/java.desktop/macosx/native/libawt_lwawt/awt/AWTWindow.m
> +     * The view hierarchy looks as follows:
Okay, thanks

2022-01-26 15:20 UTC, manu-unter commented
Grisha added a test and I believe all requested changes are done now. We also tested everything locally with Fleet on Monterey, Mojave, and High Sierra. @avu what do you think?

2022-01-26 17:53 UTC, avu requested changes

2022-01-26 17:53 UTC, avu commented on src/java.desktop/macosx/classes/sun/lwawt/macosx/CPlatformWindow.java
> +    private volatile List<Rectangle> customDecorHitTestSpots;
I think that it's better to use just a reference to Shape here (it has contains() method) and if you need several shapes just use Path2D.

2022-01-26 17:53 UTC, avu commented on src/java.desktop/macosx/classes/sun/lwawt/macosx/CPlatformWindow.java
> +    private void setCustomDecorationHitTestSpots(List<Rectangle> hitTestSpots) {
I think that we need to replace a reflection here with our JBRapi (see example test/jdk/jb/java/api/frontend/FileDialogTest.java) to use inside IDEA. We found it difficult to support random reflection calls across the code. It's really easy to lose such functionality during later updates from OpenJDK upstream. We can do it either now or in a separate pull request.

2022-01-26 19:23 UTC, merged