Asemenov/jbr 4170 2
JetBrains/JetBrainsRuntime pull request #190
Opened 2022-12-01 16:11 UTC by savoptik

2022-12-01 16:24 UTC, JB-Dmitry commented on make/modules/java.desktop/lib/Awt2dLibraries.gmk
> +    LIBS_linux :=  $(LIBDL) -lspeechd -lglib-2.0, \
Should we update README.md with respect to the libraries required to build JBR, or these libraries are expected to be found on any compatible systems?

Same question for Windows-related change below.

2022-12-01 21:47 UTC, NikitkoCent commented on make/modules/java.desktop/lib/Awt2dLibraries.gmk
> +    LIBS_linux :=  $(LIBDL) -lspeechd -lglib-2.0, \
About Windows:
https://learn.microsoft.com/en-us/windows/win32/rpc/developing-32-bit-windows-applications says that the new required library is shipped with Windows SDK and I don't think it's possible to install Visual C++ toolchain without Windows SDK.

2022-12-02 09:22 UTC, JB-Dmitry commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/AccessibleAnnouncer.c
> +        const char *msg = JNU_GetStringPlatformChars(env, str, JNI_FALSE);
Passing `JNI_FALSE` as a `jboolean*` parameter probably works, but is untidy. Passing `NULL` would be better.

2022-12-02 09:25 UTC, JB-Dmitry commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/AccessibleAnnouncer.c
> +    }
AFAIU, you need to release memory occupied by `msg` using `JNU_ReleaseStringPlatformChars`.

2022-12-02 09:36 UTC, JB-Dmitry commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/AccessibleAnnouncerJNIUtils.h
> +jclass jc_AccessibleAnnouncerUtilities = NULL;
I'm not a big C expert, but AFAIK defining variables in a header file is a bad practice. If this header file is included into multiple source files, it can cause problems.

2022-12-02 09:42 UTC, JB-Dmitry commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/OrcaConf.c
> +        const char *sintName = JNU_GetStringPlatformChars(env, jStr, JNI_FALSE);
Same problems here - `jboolean` passed to `jboolean*` typed parameter, and the returned memory insn't released.

2022-12-02 09:42 UTC, JB-Dmitry commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/OrcaConf.c
> +        const char *lang = JNU_GetStringPlatformChars(env, jStr, JNI_FALSE);
Same.

2022-12-02 09:43 UTC, JB-Dmitry commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/OrcaConf.c
> +        const char *voiceName = JNU_GetStringPlatformChars(env, jStr, JNI_FALSE);
Same

2022-12-02 09:45 UTC, JB-Dmitry commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/AccessibleAnnouncer.c
> +                    (*env)->DeleteLocalRef(env, conf);
Deleting a local reference isn't strictly necessary - it'll be automatically deleted at the end of JNI method. It can only make sense if it's anticipated that the method will not exit soon, and we should allow GC to clean it sooner.

2022-12-02 09:45 UTC, JB-Dmitry commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/AccessibleAnnouncer.c
> +                spd_close(connection);
Shouldn't this be inside `if (connection != NULL)` branch?

2022-12-02 09:47 UTC, JB-Dmitry commented on src/java.desktop/macosx/native/libawt_lwawt/awt/a11y/CommonComponentAccessibility.h
> ++ (void)postAnnounceWithCaller:(id _Nonnull)coller andText:(NSString * _Nonnull)text andPriority:(NSNumber * _Nonnull)priority;
Is `coller` a typo?

2022-12-02 10:20 UTC, JB-Dmitry commented on src/java.desktop/unix/classes/sun/awt/AccessibleAnnouncerUtilities.java
> +                    if (ch == '\n') builder.append("\n");
I wonder why this branch exists. It seems to produce the same result as the other branch.

2022-12-02 10:24 UTC, JB-Dmitry commented on src/java.desktop/unix/classes/sun/awt/AccessibleAnnouncerUtilities.java
> +                    char ch = it.next();
We might end up writing \uFFFF to the error string. It's probably better to use `it.current()` here, and advance iterator after that.

2022-12-02 10:35 UTC, JB-Dmitry commented on src/java.desktop/unix/classes/sun/awt/AccessibleAnnouncerUtilities.java
> +                            builder.append(ch);
Not sure how important is this for this use case, but looks like we're not handling \b, \f, \n, \r, \t sequences here.

2022-12-02 10:37 UTC, JB-Dmitry commented on src/java.desktop/unix/classes/sun/awt/AccessibleAnnouncerUtilities.java
> +                    if (it.current() == ',') it.next();
Probably not very important, but this will also accept the sequence of object 'fields' not separated by commas.

2022-12-02 10:37 UTC, JB-Dmitry commented on src/java.desktop/unix/classes/sun/awt/AccessibleAnnouncerUtilities.java
> +                    if (it.current() == ',') it.next();
Probably not very important, but this will also accept the sequence of array elements not separated by commas.

2022-12-02 10:39 UTC, JB-Dmitry commented on src/java.desktop/unix/classes/sun/awt/AccessibleAnnouncerUtilities.java
> +        return value instanceof Integer intValue ? intValue : null;
Looks like this will never return some value, as all numbers are represented as `Double`-s.

2022-12-02 10:45 UTC, JB-Dmitry commented on test/jdk/java/awt/a11y/AccessibleAnnouncerTest.java
> +    void createPreoretyTest() {
Did you mean 'priority'?

2022-12-02 10:47 UTC, JB-Dmitry commented on test/jdk/java/awt/a11y/AccessibleAnnouncerTest.java
> +            + "If you can hear text from text filt tab further and press PASS, otherwise press FAIL.\n";;
'filt' looks like a typo.

2022-12-02 10:49 UTC, JB-Dmitry commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/NVDAClient.h
> +// Licensed under the Apache License, Version 2.0 (the "License");
I doubt that Apache license should be used.

2022-12-02 10:54 UTC, JB-Dmitry commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/NVDAClient.cpp
> +            return 1 + wStrLen(str + 1);
Doesn't look like the most efficient way to compute the string length.

2022-12-02 11:02 UTC, JB-Dmitry commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/NVDAClient.cpp
> +            const size_t charsWritten = bytesWritten / sizeof(*buf) + bytesWritten % sizeof(*buf);
Somewhat strange way to calculate `charsWritten`. It seems to provide a correct result only when `sizeof(*buf)` is equal to 2. If we want a generic code, that'll work in any case, maybe a different formula should be used, e.g.
`(bytesWritten + sizeof(*buf) - 1)/ sizeof(*buf)`

2022-12-02 11:06 UTC, JB-Dmitry commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/NVDAAnnouncer.cpp
> +    const jchar* const jchars = env->GetStringChars(str, nullptr);
The allocated memory isn't released afterwards.

2022-12-02 12:14 UTC, NikitkoCent commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/NVDAClient.cpp
> +            return 1 + wStrLen(str + 1);
It happens only in the compile-time, so I think its efficiency doesn't matter.

2022-12-02 12:15 UTC, NikitkoCent commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/NVDAAnnouncer.cpp
> +    const jchar* const jchars = env->GetStringChars(str, nullptr);
Thanks a lot! Forgot to do it.

2022-12-04 21:52 UTC, NikitkoCent commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/NVDAAnnouncer.cpp
> +    const jchar* const jchars = env->GetStringChars(str, nullptr);
Fixed.

2022-12-04 21:52 UTC, NikitkoCent commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/NVDAClient.cpp
> +            const size_t charsWritten = bytesWritten / sizeof(*buf) + bytesWritten % sizeof(*buf);
Thanks! Fixed.

2022-12-04 21:53 UTC, NikitkoCent commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/NVDAClient.h
> +// Licensed under the Apache License, Version 2.0 (the "License");
Thanks! Fixed.

2022-12-05 09:11 UTC, JB-Dmitry commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/NVDAClient.cpp
> +            return 1 + wStrLen(str + 1);
That's OK, I guess, if that's indeed only computed at compile time.
If the compiler is smart enough to calculate this at compile time, I'd also be not surprised if it also could optimize away `wcslen` call for a string literal...

2022-12-05 10:32 UTC, savoptik commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/AccessibleAnnouncer.c
> +        const char *msg = JNU_GetStringPlatformChars(env, str, JNI_FALSE);
Done

2022-12-05 10:33 UTC, savoptik commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/AccessibleAnnouncer.c
> +    }
Done

2022-12-05 10:34 UTC, savoptik commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/AccessibleAnnouncerJNIUtils.h
> +jclass jc_AccessibleAnnouncerUtilities = NULL;
Done

2022-12-05 10:35 UTC, savoptik commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/OrcaConf.c
> +        const char *sintName = JNU_GetStringPlatformChars(env, jStr, JNI_FALSE);
Done

2022-12-05 10:35 UTC, savoptik commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/OrcaConf.c
> +        const char *lang = JNU_GetStringPlatformChars(env, jStr, JNI_FALSE);
Done

2022-12-05 10:36 UTC, savoptik commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/OrcaConf.c
> +        const char *voiceName = JNU_GetStringPlatformChars(env, jStr, JNI_FALSE);
Done

2022-12-05 10:36 UTC, savoptik commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/AccessibleAnnouncer.c
> +                spd_close(connection);
Done

2022-12-05 10:37 UTC, savoptik commented on src/java.desktop/macosx/native/libawt_lwawt/awt/a11y/CommonComponentAccessibility.h
> ++ (void)postAnnounceWithCaller:(id _Nonnull)coller andText:(NSString * _Nonnull)text andPriority:(NSNumber * _Nonnull)priority;
Done

2022-12-05 10:39 UTC, savoptik commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/AccessibleAnnouncer.c
> +                    (*env)->DeleteLocalRef(env, conf);
Thank you. But if this is not a mistake, then I will leave it as it is.

2022-12-05 10:51 UTC, savoptik commented on test/jdk/java/awt/a11y/AccessibleAnnouncerTest.java
> +    void createPreoretyTest() {
Done

2022-12-05 10:51 UTC, savoptik commented on test/jdk/java/awt/a11y/AccessibleAnnouncerTest.java
> +            + "If you can hear text from text filt tab further and press PASS, otherwise press FAIL.\n";;
Done

2022-12-05 10:52 UTC, JB-Dmitry commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/AccessibleAnnouncer.c
> +                    (*env)->DeleteLocalRef(env, conf);
I wouldn't call it a mistake, it's just an unneeded work - it only makes sense if `spd_close` can take a lot of time to execute. It won't harm in any case.

2022-12-05 22:40 UTC, NikitkoCent commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/NVDAClient.cpp
> +            return 1 + wStrLen(str + 1);
The problem with `wcslen` is that we can't force the compiler to run this function at compile-time, because it isn't marked as `constexpr`. But our function is marked as `constexpr`, so it can be run at compile-time and we force the compiler to do it by assigning it's result to a `constexpr` variable.

2022-12-07 09:26 UTC, mkartashev requested changes

2022-12-07 10:41 UTC, savoptik commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/AccessibleAnnouncer.c
> +                    (*env)->DeleteLocalRef(env, conf);
Done

2022-12-07 11:01 UTC, savoptik commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/AccessibleAnnouncerJNIUtils.h
> +jc_AccessibleAnnouncerUtilities = (*env)->FindClass(env, "Lsun/awt/AccessibleAnnouncerUtilities;");\
Done

2022-12-07 15:02 UTC, savoptik commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/OrcaConf.c
> +        int volume = gain * 20 - 100;
Done

2022-12-07 15:02 UTC, savoptik commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/AccessibleAnnouncerJNIUtils.h
> +jc_AccessibleAnnouncerUtilities = (*env)->FindClass(env, "Lsun/awt/AccessibleAnnouncerUtilities;");\
Done

2022-12-07 15:03 UTC, savoptik commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/AccessibleAnnouncerJNIUtils.h
> +jc_AccessibleAnnouncerUtilities = (*env)->FindClass(env, "Lsun/awt/AccessibleAnnouncerUtilities;");\
done

2022-12-08 06:28 UTC, mkartashev requested changes
There are still unresolved comments.

2022-12-08 06:49 UTC, mkartashev commented on test/jdk/java/awt/a11y/AccessibleAnnouncerTest.java
> +        exceptionString = "Accessible announcer preorety test failed!";
There's a misprint in the word `preorety`.

2022-12-08 07:52 UTC, savoptik commented on test/jdk/java/awt/a11y/AccessibleAnnouncerTest.java
> +        exceptionString = "Accessible announcer preorety test failed!";
Done

2022-12-08 12:25 UTC, NikitkoCent commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/NVDAClient.cpp
> +            if (!GetUserObjectInformationW(hDesk, UOI_NAME, buf, charsCapacity * sizeof(*buf), &bytesWritten)) {
I'm going to discard this part, because we've agreed to link dynamically to a third-party NVDA client dll

2022-12-08 12:27 UTC, NikitkoCent commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/NVDAClient.cpp
> +        if ((buf == nullptr) || (charsCapacity < 1)) {
I'm going to discard this part, because we've agreed to link dynamically to a third-party NVDA client dll

2022-12-08 12:27 UTC, NikitkoCent commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/NVDAClient.cpp
> +            const size_t charsWritten = bytesWritten / sizeof(*buf) + (bytesWritten % sizeof(*buf) > 0 ? 1 : 0);
I'm going to discard this part, because we've agreed to link dynamically to a third-party NVDA client dll

2022-12-14 23:04 UTC, NikitkoCent commented on test/jdk/java/awt/a11y/AccessibleAnnouncerTest.java
> + * @test
Shouldn't we mark this as manual?

2022-12-20 18:14 UTC, avu requested changes

2022-12-20 18:14 UTC, avu commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/AccessibleAnnouncer.c
> +			jobject conf = OrcaGetConf(env);
Code alignment

2022-12-20 18:14 UTC, avu commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/AccessibleAnnouncer.c
> +                if (connection != NULL)
Code alignment

2022-12-22 08:39 UTC, savoptik commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/AccessibleAnnouncer.c
> +                if (connection != NULL)
done

2022-12-22 08:40 UTC, savoptik commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/AccessibleAnnouncer.c
> +			jobject conf = OrcaGetConf(env);
Done

2022-12-22 11:42 UTC, YaaZ commented on make/modules/java.desktop/lib/Awt2dLibraries.gmk
> +        delayimp.lib jvm.lib $(WIN_JAVA_LIB) advapi32.lib dwmapi.lib rpcrt4.lib, \
Already fixed: https://github.com/JetBrains/JetBrainsRuntime/commit/3f0d0c5e56fc828dc7dcf7fb2aa1568c35d5d523#diff-c75e2d581b3730cf900075cedb66ac72eaba40fbbd92eaac5710161830b572b4R185

2023-01-03 17:27 UTC, NikitkoCent commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/NVDAClient.cpp
> +            if (!GetUserObjectInformationW(hDesk, UOI_NAME, buf, charsCapacity * sizeof(*buf), &bytesWritten)) {
The part was discarded.

2023-01-03 17:27 UTC, NikitkoCent commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/NVDAClient.cpp
> +            const size_t charsWritten = bytesWritten / sizeof(*buf) + (bytesWritten % sizeof(*buf) > 0 ? 1 : 0);
The part was discarded.

2023-01-03 17:27 UTC, NikitkoCent commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/NVDAClient.cpp
> +        if ((buf == nullptr) || (charsCapacity < 1)) {
The part was discarded.

2023-01-03 20:32 UTC, NikitkoCent commented on README.md
> +If you want to add support of NVDA screen reader (for a11y reasons), you will need to bundle the NVDA Controller Client library.
Done.

2023-01-03 20:33 UTC, NikitkoCent commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/NVDAAnnouncer.cpp
> +        // TODO: add some error handling
Thanks! Done.

2023-01-03 20:33 UTC, NikitkoCent commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/NVDAAnnouncer.cpp
> +        // TODO: add some error handling
Replaced by `DASSERT` here.

2023-01-04 18:56 UTC, NikitkoCent requested changes
Several unresolved comments

2023-01-04 18:56 UTC, NikitkoCent commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/NVDAAnnouncer.cpp
> +            // TODO: add some error handling
An unattended TODO.

2023-01-04 18:56 UTC, NikitkoCent commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/NVDAAnnouncer.cpp
> +        // TODO: add some error handling
An unattended TODO.

2023-01-04 18:56 UTC, NikitkoCent commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/NVDAAnnouncer.h
> +// TODO: reconsider the data type is used for error reporting (maybe the bool isn't informative enough)
An unattended TODO.

2023-01-04 18:56 UTC, NikitkoCent commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/AccessibleAnnouncer.cpp
> +            // TODO: add some error handling?
An unattended TODO.

2023-01-05 08:49 UTC, savoptik commented on src/java.desktop/macosx/native/libawt_lwawt/awt/JavaAccessibilityUtilities.m
> +NSMutableDictionary *sAnnouncePriorities = nil;
Above is the sRoles variable. We did it in a similar way to sRoles. I'm thinking of leaving it like this for the sake of consistency.

2023-01-05 08:52 UTC, savoptik commented on src/java.desktop/macosx/native/libawt_lwawt/awt/a11y/CommonComponentAccessibility.m
> +                caller = [NSApp accessibilityFocusedUIElement];
The ability to pass in a calling component has been added in order to provide more convenient debugging in the future if something suddenly goes wrong.
The function to send a notification for this type of notification accepts nil without any problems.

2023-01-05 09:08 UTC, savoptik commented on src/java.desktop/macosx/native/libawt_lwawt/awt/a11y/CommonComponentAccessibility.m
> +        }];
Done.

2023-01-05 09:59 UTC, savoptik commented on src/java.desktop/share/classes/javax/swing/AccessibleAnnouncer.java
> +    public static native void announce(Accessible a, final String str, final int priority);
Done

2023-01-05 10:00 UTC, savoptik commented on src/java.desktop/share/classes/javax/swing/AccessibleAnnouncer.java
> +     * @param priority priority for announsing
done

2023-01-05 10:05 UTC, savoptik commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/OrcaConf.c
> +OrcaSetVolume(env, connection, conf);
Done

2023-01-05 10:32 UTC, savoptik commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/OrcaConf.c
> +    if (gain >= 0)
See the speech dispatcher [documentation](https://htmlpreview.github.io/?https://github.com/brailcom/speechd/blob/master/doc/speech-dispatcher.html#C-API).

2023-01-05 16:18 UTC, savoptik commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/AccessibleAnnouncer.c
> +        if (msg != NULL)
Done

2023-01-05 16:18 UTC, savoptik commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/AccessibleAnnouncer.c
> +                if (OrcaGetEnableSpeech(env, conf) > 0)
Done

2023-01-05 16:19 UTC, savoptik commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/OrcaConf.c
> +        if (lang != NULL)
Done

2023-01-05 16:22 UTC, savoptik commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/JawsAnnouncer.cpp
> +    CoInitialize(NULL);
Done

2023-01-05 16:24 UTC, savoptik commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/JawsAnnouncer.cpp
> +        pJawsApi->SayString(param, jawsPriority, &retval);
Done

2023-01-05 16:24 UTC, savoptik commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/JawsAnnouncer.cpp
> +        pJawsApi->SayString(param, jawsPriority, &retval);
Done

2023-01-05 16:27 UTC, savoptik commented on test/jdk/java/awt/a11y/AccessibleAnnouncerTest.java
> +    @java.lang.Override
So framed the IDE in the first tests. The rest I do consistently with the rest of the tests.

2023-01-10 17:59 UTC, NikitkoCent commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/AccessibleAnnouncer.c
> +                if (OrcaGetEnableSpeech(env, conf) > 0)
Returned value of `spd_say` still isn't handled.

2023-01-12 11:17 UTC, savoptik commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/AccessibleAnnouncer.c
> +                if (OrcaGetEnableSpeech(env, conf) > 0)
Done

2023-01-12 21:57 UTC, NikitkoCent requested changes
Unresolved conversations

2023-01-13 13:31 UTC, NikitkoCent commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/JawsAnnouncer.cpp
> +    CoInitialize(NULL);
Fixed

2023-01-13 13:31 UTC, NikitkoCent commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/JawsAnnouncer.cpp
> +    HRESULT hr = CoCreateInstance(CLSID_JAWSCLASS, NULL, CLSCTX_INPROC_SERVER, IID_IJAWSAPI, reinterpret_cast<void**>(&pJawsApi));
Fixed

2023-01-13 13:32 UTC, NikitkoCent commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/JawsAnnouncer.cpp
> +    if(retval != -1) {
Done.

2023-01-13 14:00 UTC, NikitkoCent requested changes
A few comments

2023-01-13 14:00 UTC, NikitkoCent commented on src/java.desktop/share/classes/sun/swing/AccessibleAnnouncer.java
> +    }
Should we validate `str` and `priority` here before passing them to the native side? This is also related to one of my previos questions: https://github.com/JetBrains/JetBrainsRuntime/pull/190#discussion_r1060948143

2023-01-13 14:00 UTC, NikitkoCent commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/OrcaAnnouncer.c
> +JNU_ThrowOutOfMemoryError(env, "OrcaAnnounce: failed to obtain chars from the announcing string");
1. Code alignment
2. Please check this: https://github.com/JetBrains/JetBrainsRuntime/pull/190#discussion_r1067191186. I think we should check that there are no any pending exceptions before throwing our one (`env->ExceptionCheck() == JNI_FALSE`)

2023-01-13 14:00 UTC, NikitkoCent commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/OrcaAnnouncer.c
> +JNU_ThrowOutOfMemoryError(env, "OrcaAnnounce: failed to obtain chars from the sintName string");
Same as https://github.com/JetBrains/JetBrainsRuntime/pull/190#discussion_r1069476942

2023-01-13 14:00 UTC, NikitkoCent commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/OrcaAnnouncer.c
> +        JNU_ThrowOutOfMemoryError(env, "OrcaAnnounce: failed to obtain chars from the voiceName string");
Same as https://github.com/JetBrains/JetBrainsRuntime/pull/190#discussion_r1069476942 (except the code alignment is ok)

2023-01-13 14:00 UTC, NikitkoCent commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/JawsAnnouncer.cpp
> +        const jchar *jchars = env->GetStringChars(str, NULL);
Fixed

2023-01-13 14:00 UTC, NikitkoCent commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/JawsAnnouncer.cpp
> +        BSTR param = SysAllocString(jchars);
Done

2023-01-16 13:50 UTC, savoptik commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/NVDAAnnouncer.h
> +// TODO: reconsider the data type is used for error reporting (maybe the bool isn't informative enough)
Done.

2023-01-16 13:51 UTC, savoptik commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/NVDAAnnouncer.cpp
> +            fprintf(stderr, "Failed to interapt current output. code = %d\n", nvdaStatus);
Done.

2023-01-16 14:13 UTC, savoptik commented on src/java.desktop/share/classes/sun/swing/AccessibleAnnouncer.java
> +    }
Done

2023-01-21 00:19 UTC, NikitkoCent commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/AccessibleAnnouncerJNIUtils.h
> +jc_AccessibleAnnouncerUtilities = (*env)->FindClass(env, "Lsun/awt/AccessibleAnnouncerUtilities;");\
I've verified that it is actually fixed, so marking as resolved.

2023-01-21 00:20 UTC, NikitkoCent commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/OrcaConf.c
> +void set_language(JNIEnv *env, SPDConnection *connection, jobject conf)
Has been renamed to `OrcaSetLanguage`.

2023-01-21 00:21 UTC, NikitkoCent commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/OrcaConf.c
> +        int iRate = rate * 2 - 100;
Not addressed yet.

2023-01-21 00:23 UTC, NikitkoCent commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/OrcaConf.c
> +            (*env)->DeleteLocalRef(env, jStr);
Fixed.

2023-01-21 00:24 UTC, NikitkoCent commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/OrcaConf.c
> +            (*env)->DeleteLocalRef(env, jStr);
Fixed.

2023-01-21 00:24 UTC, NikitkoCent commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/OrcaConf.c
> +            (*env)->DeleteLocalRef(env, jStr);
Fixed.

2023-01-21 00:26 UTC, NikitkoCent commented on src/java.desktop/share/classes/javax/swing/AccessibleAnnouncer.java
> +     * @param priority priority for announsing
Verified that it has actually been fixed.

2023-01-21 00:27 UTC, NikitkoCent commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/AccessibleAnnouncer.c
> +                SPDConnection *connection = spd_open("Cli announcer", NULL, NULL, SPD_MODE_SINGLE);
Not addressed yet

2023-01-21 00:28 UTC, NikitkoCent commented on src/java.desktop/macosx/native/libawt_lwawt/awt/JavaAccessibilityUtilities.m
> +//    [sAnnouncePriorities setObject:[NSNumber numberWithInt:NSAccessibilityPriorityHigh] forKey:[NSNumber numberWithInt:javax_swing_AccessibleAnnouncer_ACCESSIBLE_PRIORITY_HIGH]];
Verified.

2023-01-21 00:37 UTC, NikitkoCent commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/AccessibleAnnouncer.c
> +    if (str != NULL)
Looks like fixed.

2023-01-21 00:37 UTC, NikitkoCent commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/AccessibleAnnouncer.c
> +        if (msg != NULL)
Consistent fixed were made.

2023-01-21 00:40 UTC, NikitkoCent commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/OrcaConf.c
> +    if (gain >= 0)
Are there any updates?

2023-01-21 00:41 UTC, NikitkoCent commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/OrcaConf.c
> +        if (sintName != NULL)
Looks like done.

2023-01-21 00:42 UTC, NikitkoCent commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/OrcaConf.c
> +        if (lang != NULL)
Looks like done.

2023-01-21 00:42 UTC, NikitkoCent commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/OrcaConf.c
> +        if (voiceName != NULL)
Looks like done.

2023-01-21 00:42 UTC, NikitkoCent commented on src/java.desktop/share/classes/javax/swing/AccessibleAnnouncer.java
> +    public static native void announce(Accessible a, final String str, final int priority);
Done

2023-01-21 00:50 UTC, NikitkoCent commented on src/java.desktop/share/classes/sun/swing/AccessibleAnnouncer.java
> +        priority != ANNOUNCE_WITH_INTERRUPTING_CURRENT_OUTPUT) return;
Propose to throw an `IllegalArgumentException` instead of suppressing of incorrect API usage.

2023-01-21 00:50 UTC, NikitkoCent commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/OrcaAnnouncer.c
> +JNU_ThrowOutOfMemoryError(env, "OrcaAnnounce: failed to obtain chars from the sintName string");
Looks like fixed.

2023-01-21 00:50 UTC, NikitkoCent commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/OrcaAnnouncer.c
> +        JNU_ThrowOutOfMemoryError(env, "OrcaAnnounce: failed to obtain chars from the lang string");
Looks like fixed.

2023-01-21 00:50 UTC, NikitkoCent commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/OrcaAnnouncer.c
> +        JNU_ThrowOutOfMemoryError(env, "OrcaAnnounce: failed to obtain chars from the voiceName string");
Looks like fixed.

2023-01-21 00:53 UTC, NikitkoCent commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/OrcaAnnouncer.c
> +JNU_ThrowOutOfMemoryError(env, "OrcaAnnounce: failed to obtain chars from the announcing string");
Looks like fixed.

2023-01-21 00:55 UTC, NikitkoCent requested changes
A few unresolved conversations.

2023-01-21 22:15 UTC, savoptik commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/OrcaConf.c
> +    if (gain >= 0)
This knowledge was obtained empirically by studying the configuration file.
[user-settings.conf.zip](https://github.com/JetBrains/JetBrainsRuntime/files/10473183/user-settings.conf.zip)

2023-01-23 11:41 UTC, savoptik commented on src/java.desktop/share/classes/sun/swing/AccessibleAnnouncer.java
> +        priority != ANNOUNCE_WITH_INTERRUPTING_CURRENT_OUTPUT) return;
Done

2023-01-23 18:15 UTC, JB-Dmitry approved these changes

2023-01-24 17:19 UTC, NikitkoCent commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/AccessibleAnnouncer.c
> +                SPDConnection *connection = spd_open("Cli announcer", NULL, NULL, SPD_MODE_SINGLE);
Has been changed to "_Java announcer_".

2023-01-24 17:21 UTC, NikitkoCent commented on src/java.desktop/linux/native/libawt_xawt/AccessibleAnnouncer/OrcaConf.c
> +        int iRate = rate * 2 - 100;
Fixed.

2023-01-24 17:22 UTC, NikitkoCent commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/NVDAAnnouncer.cpp
> +        // TODO: add some error handling
Will mark as fixed.

2023-01-24 17:44 UTC, NikitkoCent approved these changes

2023-01-24 19:08 UTC, avu requested changes

2023-01-24 19:08 UTC, avu commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/JawsAnnouncer.cpp
> +        #ifdef DEBUG
Do not align #define  preprocessor instructions, they should start at the beginning of the line

2023-01-24 19:08 UTC, avu commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/JawsAnnouncer.cpp
> +            #ifdef DEBUG
Same here

2023-01-24 19:08 UTC, avu commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/JawsAnnouncer.cpp
> +            fprintf(stderr, "JawsAnnounce: failed to invoke COM function to say string ; HRESULT=0x%llX.\n", static_cast<unsigned long long>(comCallResult));
And here

2023-01-25 12:49 UTC, NikitkoCent commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/JawsAnnouncer.cpp
> +            #ifdef DEBUG
Fixed.

2023-01-25 12:49 UTC, NikitkoCent commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/JawsAnnouncer.cpp
> +            fprintf(stderr, "JawsAnnounce: failed to invoke COM function to say string ; HRESULT=0x%llX.\n", static_cast<unsigned long long>(comCallResult));
Fixed.

2023-01-25 14:18 UTC, avu approved these changes

2023-01-25 15:28 UTC, merged