JBR-5118 VoiceOver does not speak the label associated with the combobox
JetBrains/JetBrainsRuntime pull request #194
Opened 2022-12-20 14:32 UTC by savoptik

2022-12-20 18:00 UTC, avu requested changes

2022-12-20 19:48 UTC, savoptik commented on src/java.desktop/macosx/native/libawt_lwawt/awt/a11y/ComboBoxAccessibility.m
> +    BOOL isExpandet = isExpanded(env, [self axContextWithEnv:env], fComponent);
Done

2022-12-20 19:48 UTC, savoptik commented on src/java.desktop/macosx/native/libawt_lwawt/awt/a11y/ComboBoxAccessibility.h
> +    CommonComponentAccessibility *value;
No equivalent code is obtained.

2022-12-21 22:08 UTC, avu approved these changes

2022-12-22 07:50 UTC, merged