JBR-6543 Vulkan: migrate current code to pure c
JetBrains/JetBrainsRuntime pull request #267
Opened 2024-01-11 20:03 UTC by avu

2024-01-16 08:21 UTC, mkartashev requested changes

2024-01-16 08:21 UTC, mkartashev commented on src/java.desktop/share/native/common/java2d/cvulkan/VKBase.c
> +const char* physicalDeviceTypeString(VkPhysicalDeviceType type)
This one isn't exported by the header, so should be `static`, I guess

2024-01-16 08:21 UTC, mkartashev commented on src/java.desktop/share/native/common/java2d/cvulkan/VKBase.c
> +        geInstance = (VKGraphicsEnvironment*)malloc(sizeof(VKGraphicsEnvironment));
Better check for `malloc` failure as otherwise we're going to crash at the next line.

2024-01-16 08:21 UTC, mkartashev commented on src/java.desktop/share/native/common/java2d/cvulkan/VKBase.c
> +        geInstance->layers = (VkLayerProperties*) malloc(sizeof(VkLayerProperties)*geInstance->layersCount);
Also a `malloc` check is required here.

2024-01-16 08:21 UTC, mkartashev commented on src/java.desktop/share/native/common/java2d/cvulkan/VKBase.c
> +        geInstance->physicalDevices = malloc(sizeof (VkPhysicalDevice)*geInstance->physicalDevicesCount);
Another `malloc` check is requried.

2024-01-16 08:21 UTC, mkartashev commented on src/java.desktop/share/native/common/java2d/cvulkan/VKBase.c
> +        geInstance->devices = (VKLogicalDevice *) malloc(geInstance->physicalDevicesCount*sizeof(VKLogicalDevice));
Another `malloc` check is required.

2024-01-16 08:21 UTC, mkartashev commented on src/java.desktop/share/native/common/java2d/cvulkan/VKBase.c
> +            VkQueueFamilyProperties *queueFamilies = malloc(sizeof(VkQueueFamilyProperties) * queueFamilyCount);
Another `malloc` check is required.

2024-01-16 08:21 UTC, mkartashev commented on src/java.desktop/share/native/common/java2d/cvulkan/VKBase.c
> +            VkLayerProperties *layers = (VkLayerProperties *) malloc(layerCount * sizeof(VkLayerProperties));
Another `malloc` check is required.

2024-01-16 08:21 UTC, mkartashev commented on src/java.desktop/share/native/common/java2d/cvulkan/VKBase.c
> +            VkExtensionProperties *extensions = (VkExtensionProperties *) malloc(
Another `malloc` check is required.

2024-01-16 08:21 UTC, mkartashev commented on src/java.desktop/share/native/common/java2d/cvulkan/VKBase.c
> +            char **deviceEnabledLayers = malloc(MAX_ENABLED_LAYERS * sizeof(char *));
Another `malloc` check is required.

2024-01-16 08:21 UTC, mkartashev commented on src/java.desktop/share/native/common/java2d/cvulkan/VKBase.c
> +            char **deviceEnabledExtensions = malloc(MAX_ENABLED_EXTENSIONS * sizeof(char *));
Another `malloc` check is required.

2024-01-16 08:21 UTC, mkartashev commented on src/java.desktop/share/native/common/java2d/cvulkan/VKBase.c
> +            geInstance->devices[i].name = malloc(strlen(deviceProperties2.properties.deviceName) + 1);
Another `malloc` check is required.

2024-01-16 08:21 UTC, mkartashev commented on src/java.desktop/share/native/common/java2d/cvulkan/VKBase.c
> +            geInstance->devices[i].name = malloc(strlen(deviceProperties2.properties.deviceName) + 1);
Alternatively, you can use `strdup` instead of malloc/strcpy

2024-01-16 08:21 UTC, mkartashev commented on src/java.desktop/share/native/common/java2d/cvulkan/VKBase.c
> +        geInstance->extensions = (VkExtensionProperties*) malloc(sizeof(VkExtensionProperties)*geInstance->extensionsCount);
Another `malloc` check is required.

2024-01-17 08:43 UTC, mkartashev approved these changes

2024-01-17 08:43 UTC, mkartashev commented on src/java.desktop/share/native/common/java2d/cvulkan/VKRenderQueue.h
> +#define SKIP_BYTES(buf, numbytes) (buf) += (numbytes)
Maybe cast buf to char* to be on the safe side and ensure that it is bytes that are skipped?

2024-01-17 08:43 UTC, mkartashev commented on src/java.desktop/share/native/common/java2d/cvulkan/VKSurfaceData.h
> +typedef struct _VKSDOps VKSDOps;
Strictly speaking, an identifier starting with an underscore followed by an uppercase letter is reserved in C, so it's better to have the underscore at the end.

2024-01-18 20:05 UTC, YaaZ requested changes

2024-01-19 18:50 UTC, avu commented on src/java.desktop/share/native/common/java2d/cvulkan/VKBase.c
> +    requestedDeviceNumber = requestedDevice;
I think we need to support both ways, probably we can have special invalid value like -1 to automatically select the best device.

2024-01-19 19:04 UTC, avu commented on src/java.desktop/share/native/common/java2d/cvulkan/VKBase.c
> +        *geInstance = (VKGraphicsEnvironment) {
I'm not sure how calloc can help here, but I can put some comments describing each default value. The reason of the approach above is not to miss initializer after possible extension of the structure

2024-01-19 22:39 UTC, avu commented on src/java.desktop/share/native/common/java2d/cvulkan/VKSurfaceData.c
> +#define VKSD_RT_TEXTURE      sun_java2d_pipe_hw_AccelSurface_RT_TEXTURE
These types have simple meaning: window, usual texture, texture that can be render target. I suppose that it could be useful for us to have such abstractions.

2024-03-20 23:06 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/cvulkan/VKBase.c
> +    VkRenderPassCreateInfo renderPassInfo = {};
Overall, render passes are too inflexible for our use case, we need to support them as a backup, but prefer dynamic rendering extension when supported.

2024-03-26 12:55 UTC, avu commented on src/java.desktop/share/native/common/java2d/cvulkan/VKBase.c
> +    VkRenderPassCreateInfo renderPassInfo = {};
Let's start with minimal supported API and then provide advanced features.

2024-03-26 13:28 UTC, avu commented on src/java.desktop/share/native/common/java2d/cvulkan/VKBase.c
> +    if (vkCreatePipelineCache(device, &pipelineCacheCreateInfo, NULL, &logicalDevice->pipelineCache) != VK_SUCCESS)
Let's keep it here for now

2024-03-26 13:31 UTC, avu commented on src/java.desktop/share/native/common/java2d/cvulkan/VKBase.c
> +    if (requestedDeviceNumber < 0 || (uint32_t)requestedDeviceNumber >= geInstance->devicesCount) {
OK, let's keep this way for now and reconsider later if necessary.

2024-04-20 16:15 UTC, YaaZ requested changes
Overall it's much cleaner now, C API is not THAT bad after all :)

2024-04-20 16:15 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/cvulkan/VKSurfaceData.c
> +        uint32_t imageCount = vkwinsdo->capabilitiesKhr.minImageCount + 1;
What is the reason behind this `minImageCount + 1`? I think we should decide on the number of images in conjunction with the `presentMode`

2024-04-20 16:15 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/cvulkan/VKSurfaceData.c
> +        createInfoKhr.imageColorSpace = vkwinsdo->formatsKhr[0].colorSpace;
TODO: the first reported format is not always the easiest "default" format, so we will need some more logic here.
We also need to use this format when creating the render pass, currently we are using hardcoded `VK_FORMAT_B8G8R8A8_UNORM` there

2024-04-20 16:15 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/cvulkan/VKSurfaceData.c
> +        createInfoKhr.presentMode = VK_PRESENT_MODE_FIFO_KHR;
TODO: inspect available modes and choose something better?

2024-04-20 16:15 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/cvulkan/VKSurfaceData.c
> +        vkwinsdo->swapChainImageViews = calloc(vkwinsdo->swapChainImageViewsCount, sizeof(VkImageView));
Maybe use new dynamic arrays here?

2024-04-24 23:08 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/cvulkan/VKSurfaceData.c
> +        createInfoKhr.imageColorSpace = vkwinsdo->formatsKhr[0].colorSpace;
Also, `VK_FORMAT_B8G8R8A8_UNORM` may be wrong too. If we want to work in sRGB color space (do we?), then we can get gamma correction done by the hardware with `_SRGB` formats.

2024-04-26 15:55 UTC, avu commented on src/java.desktop/share/native/common/java2d/cvulkan/CArrayUtil.h
> +    size_t elem_size;
It's used for reallocation of the array to provide more space (see CArrayUtil.c CARR_array_realloc)

2024-04-26 16:50 UTC, avu commented on src/java.desktop/share/native/common/java2d/cvulkan/VKBase.c
> +    if (geInstance->vkCreateGraphicsPipelines(device, VK_NULL_HANDLE, 1, &pipelineInfo, NULL,
I decided to remove the cache to simplify the code

2024-04-26 16:52 UTC, avu commented on src/java.desktop/share/native/common/java2d/cvulkan/VKRenderQueue.c
> +    if (dstOps != NULL && dstOps->drawableType == VKSD_WINDOW) {
FLUSH_SURFACE is used before the disposal of the surface. We put the rendering here to commit all the changes that were rendered into the window surface buffer

2024-04-26 17:28 UTC, avu commented on src/java.desktop/share/native/common/java2d/cvulkan/VKSurfaceData.c
> +        uint32_t imageCount = vkwinsdo->capabilitiesKhr.minImageCount + 1;
I didn't want to allocate too many images

2024-04-26 22:49 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/cvulkan/VKBase.c
> +    if (geInstance->vkCreateGraphicsPipelines(device, VK_NULL_HANDLE, 1, &pipelineInfo, NULL,
I think we need it anyway, pipeline creation performance would benefit from it even if we will not store it to the disk (and even more if we will)

2024-04-26 23:01 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/cvulkan/CArrayUtil.h
> +    size_t elem_size;
Sure, it is only used in reallocation, but this is such a compile time constant which is not usually stored explicitly. When adding an element and trying to reallocate an array we could probably get it from the parameter via sizeof

2024-04-26 23:06 UTC, tsarn commented on src/java.desktop/share/native/common/java2d/cvulkan/VKRenderQueue.c
> +        ge->vkAcquireNextImageKHR(logicalDevice->device, winDstOps->swapchainKhr, UINT64_MAX,
I would add a TODO: handle swapchain lost/not optimal errors

2024-04-26 23:19 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/cvulkan/VKSurfaceData.c
> +        uint32_t imageCount = vkwinsdo->capabilitiesKhr.minImageCount + 1;
I mean, usual logic for choosing number of images is not to use `minImageCount` as a basis, but rather as a lower bound. `presentMode` should be a basis instead, for example in `IMMEDIATE` mode there's no reason to have more than one image, or there is no reason to have `MAILBOX` with two images, as then it will be identical to `FIFO`

2024-04-26 23:21 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/cvulkan/VKRenderQueue.c
> +        ge->vkAcquireNextImageKHR(logicalDevice->device, winDstOps->swapchainKhr, UINT64_MAX,
True, this will fire on window resize

2024-05-27 15:59 UTC, YaaZ approved these changes

2024-05-27 15:59 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/vulkan/VKBase.c
> +    // Create command pull
Typo "pull" -> "pool". Overall, we would need to refactor this to manage command buffers and synchronization primitives, as having one per device would kill the throughput.

2024-05-27 15:59 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/vulkan/VKBase.c
> +    ARRAY_FREE(vertices);
Why do we need this? We can render a full-screen quad with a simple vertex shader and without any vertex input at all. That would simplify the pipeline creation and we wouldn't need to create and bind the buffer.

2024-05-27 15:59 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/vulkan/VKSurfaceData.c
> +    ARRAY_PUSH_BACK(&cVertices, ((VKCVertex){-1.0f, -1.0f, RGBA_TO_L4(vksdo->bgColor)}));
I think we better make color a per-instance attribute instead of per-vertex

2024-05-27 15:59 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/vulkan/VKSurfaceData.c
> +    }
Why do we create a full-screen quad vertex buffer for each surface?

2024-05-27 15:59 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/vulkan/VKSurfaceData.c
> +        }
I think this belongs in `VKSD_InitImageSurface`

2024-05-28 16:20 UTC, avu commented on src/java.desktop/share/native/common/java2d/vulkan/VKBase.c
> +    ARRAY_FREE(vertices);
Yes, we can add a separate shader with embedded coordinates. Here I've reused the shader that will be used for blitting arbitrary areas

2024-05-28 16:37 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/vulkan/VKBase.c
> +    ARRAY_FREE(vertices);
Even if we are blitting arbitrary area, if we are doing one draw call per rectangle, it will be much easier to go with the same vertex shader and specify position/size via push constants which will be recorded directly into the command buffer. If we are going to do batch blit with a single draw call, then sure we would better go with ordinary vertex buffer, but then we would need to support growing vertex buffer, maintain a pool or something

2024-05-28 16:39 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/vulkan/VKSurfaceData.c
> +    ARRAY_PUSH_BACK(&cVertices, ((VKCVertex){-1.0f, -1.0f, RGBA_TO_L4(vksdo->bgColor)}));
Note: this relates to the previous question about `flat` modifier. If we do need to support gradient with the same pipeline, then we cannot make it a per-instance attribute, of course

2024-05-28 16:52 UTC, avu commented on src/java.desktop/share/native/common/java2d/vulkan/VKBase.c
> +    ARRAY_FREE(vertices);
I suppose we'll have both. For scan-converted shapes there will be bulk rendering, for rectangular blits there will be one draw call.

2024-05-28 16:54 UTC, avu commented on src/java.desktop/share/native/common/java2d/vulkan/VKSurfaceData.c
> +    ARRAY_PUSH_BACK(&cVertices, ((VKCVertex){-1.0f, -1.0f, RGBA_TO_L4(vksdo->bgColor)}));
Usually, we have a separate shader for gradients, because they may have multiple stops or they may be radial with multiple stops

2024-05-28 16:56 UTC, avu commented on src/java.desktop/share/native/common/java2d/vulkan/VKSurfaceData.c
> +    }
I've not decided at that moment where to put such global data but in case of separate shader we don't need it anyway

2024-05-28 22:35 UTC, avu commented on src/java.desktop/share/native/common/java2d/cvulkan/VKVertex.h
> +#define RGBA_TO_L4(c)              \
I'll check but looks like we have this problem for metal and opengl.

2024-05-29 17:47 UTC, merged

2024-05-29 18:43 UTC, mkurz commented
How ready is Vulkan in the JBR now? Usable?

2024-05-30 14:53 UTC, avu commented
@mkurz Not yet it's in the early stage hopefully we'll have something relatively feature-complete in several months.