JBR-6593 Fix UI freezes with JAWS announcements
JetBrains/JetBrainsRuntime pull request #272
Opened 2024-01-23 13:03 UTC by dmitrii-drobotov

* Execute `AccessibleAnnouncer.nativeAnnounce` on a background thread on Windows to fix UI freezes. IntelliJ calls this method from EDT, but it doesn't need to run on EDT because on Windows it simply calls screen readers API without interacting with UI components. Additionally, when using a background thread, the JAWS `SayString` method, which previously could have been running for multiple seconds, is now executed immediately as expected, but the root cause of previous delays is unclear.
* In `JawsAnnouncer`, initialize COM library with the multithreaded model to allow executing it from different threads. Now COM is initialized and uninitialized on every call of the method as required by the [documentation](https://learn.microsoft.com/en-us/windows/win32/learnwin32/initializing-the-com-library): "Each thread that uses a COM interface must make a separate call to this function. For every successful call to CoInitializeEx, you must call CoUninitialize before the thread exits". The `IJawsApi` COM object is still static and reused by different threads, which is allowed with a multithreaded concurrency model. It shouldn't cause issues because it has no state and only forwards calls to JAWS.

Tested on jbr17, jbr21 and main.

2024-02-19 04:07 UTC, NikitkoCent requested changes
There're one important question and one not important improvement suggestion.

2024-02-19 04:07 UTC, NikitkoCent commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/JawsAnnouncer.cpp
> +    ComInitializationWrapper comInitializer;
We can try to use TLS to avoid initializing/uninitializing COM on each call of the announcing API:
```cpp
static THREAD_LOCAL ComInitializationWrapper comInitializer;
```
AFAIU, the JAWS announcing API is gonna be used on one specific thread only (which isn't EDT, but still only one specific), hence such an improvement will keep only one thread with initialized COM through the lifetime of the app.

2024-02-20 15:20 UTC, dmitrii-drobotov commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/JawsAnnouncer.cpp
> +            m_initializeResult = CoInitializeEx(nullptr, COINIT_MULTITHREADED);
I tested it now by changing the boot java runtime in a production build and it works fine, `CoInitializeEx` still returns `S_OK`. The jump list feature, which I assume uses `winshellintegrationbridge`, also works well. 

The [documentation](https://learn.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-coinitializeex) doesn't mention this specific case, but it seems that `CoInitializeEx` is separate for every thread, so if we initialize it differently from different threads, it should be fine.

2024-02-20 15:25 UTC, dmitrii-drobotov commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/JawsAnnouncer.cpp
> +    ComInitializationWrapper comInitializer;
Good idea, I added it. I think it's possible that it will use a different thread later based on https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/Executors.html#newSingleThreadExecutor(): "Note however that if this single thread terminates due to a failure during execution prior to shutdown, a new one will take its place if needed to execute subsequent tasks". But because it will a be a single thread at a time, thread_local should work.

2024-02-26 17:11 UTC, NikitkoCent requested changes
Asked for the `thread_local` -> `THREAD_LOCAL` change

2024-02-26 18:25 UTC, dmitrii-drobotov commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/JawsAnnouncer.cpp
> +    ComInitializationWrapper comInitializer;
`THREAD_LOCAL` causes compilation issues, that's why I assumed it should be `thread_local`. Looks like it's defined in hotspot module and not accessible here:
```
src\java.desktop\windows\native\libawt\windows\AccessibleAnnouncer\JawsAnnouncer.cpp(111): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
src\java.desktop\windows\native\libawt\windows\AccessibleAnnouncer\JawsAnnouncer.cpp(111): error C2146: syntax error: missing ';' before identifier 'ComInitializationWrapper'
```

Should I remove it then?

2024-02-27 09:42 UTC, dmitrii-drobotov commented on src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/JawsAnnouncer.cpp
> +    ComInitializationWrapper comInitializer;
Done.

2024-02-27 16:32 UTC, NikitkoCent approved these changes

2024-02-27 17:29 UTC, merged