JBR-6746 Fix linux build failing on: "error: 'this' pointer is null"
JetBrains/JetBrainsRuntime pull request #314
Opened 2024-02-23 20:41 UTC by skybber

2024-02-26 16:23 UTC, NikitkoCent requested changes
Without this patch, `jbr17` branch fails to build on my env (with the errors described in [JBR-6746](https://youtrack.jetbrains.com/issue/JBR-6746/)) with the following configure arguments:
`--enable-option-checking=fatal --with-jtreg=<...> --with-boot-jdk=<...> --with-debug-level=fastdebug --with-conf-name=jbr17-fastdebug`

With the patch applied, jbr17 branch successfully builds with the same configure parameters.

However, there's 1 follow-up question.

2024-02-26 16:23 UTC, NikitkoCent commented on src/hotspot/share/prims/jvmtiEnhancedRedefineClasses.cpp
> +          if (old_field->is_internal() && old_field->name_internal_dcevm() == internal_field->name_internal_dcevm()) {
Just to make sure: there's no need here to additionally check `internal_field->is_internal()`, because it's always supposed to be so, right?

2024-02-26 19:23 UTC, skybber commented on src/hotspot/share/prims/jvmtiEnhancedRedefineClasses.cpp
> +          if (old_field->is_internal() && old_field->name_internal_dcevm() == internal_field->name_internal_dcevm()) {
Yes, there is no need, parameters are passed from `InstanceKlass::do_nonstatic_fields_dcevm` and `internal_field` is always internal field, but your suggestion clarifies the code, so I'll incorporate it.

2024-02-26 19:38 UTC, NikitkoCent approved these changes

2024-05-15 11:03 UTC, NikitkoCent commented
Have already been merged.

2024-05-15 11:03 UTC, closed without merging