JBR-6763 Wayland: handle popup_done event
JetBrains/JetBrainsRuntime pull request #323
Opened 2024-02-27 21:32 UTC by xdom

Certain Wayland compositors (wlroots) invalidate xdg_surface after window with popup loses focus. Subsequent attempts to commit the popup window fail with protocol error
"xdg_surface has never been configured".

Handle popup_done event by hiding the popup window and emitting WINDOW_CLOSING Window event.

2024-02-28 06:01 UTC, mkartashev commented
Thank you for reporting the problem and the solution! I'm going to need some time to set up wlroots and then I will get back to you

2024-02-29 09:07 UTC, mkartashev commented
I have not been able to reproduce that on the version of Sway that I have: 1.7. Can provide some more details on how to reproduce the issue?

2024-02-29 10:27 UTC, mkartashev requested changes

2024-02-29 10:27 UTC, mkartashev commented on src/java.desktop/unix/classes/sun/awt/wl/WLComponentPeer.java
> +            WLToolkit.postEvent(new WindowEvent((Window) target, WindowEvent.WINDOW_CLOSING));
Normally, popups do not generate this event when closing. Are you certain this is needed?

2024-02-29 10:27 UTC, mkartashev commented on src/java.desktop/unix/classes/sun/awt/wl/WLComponentPeer.java
> +            setVisible(false);
Since it is not being called through the "norma" chain (`Component.setVisible()`), we now risk getting another `setVisible(false)` call later, which will probably be harmful. Could you please guard against that in `WLComponentPeer.wlSetVisible()`. Also, the `WLComponentPeer.visible` flag should be accessed under `synchronized(getStateLock())`; could you also add that, please?

2024-02-29 10:27 UTC, mkartashev commented on src/java.desktop/unix/native/libawt_wlawt/WLComponentPeer.c
> +    struct WLFrame *frame = (struct WLFrame *) data;
The cast to `(struct WLFrame *)` is unnecessary here.

2024-03-04 08:37 UTC, mkartashev commented on src/java.desktop/unix/classes/sun/awt/wl/WLComponentPeer.java
> +            WLToolkit.postEvent(new WindowEvent((Window) target, WindowEvent.WINDOW_CLOSING));
Then please leave a comment to that effect above the `postEvent` call; we may need to revisit this later and should know how to reproduce the issue that line is supposed to solve.
Thanks!

2024-03-04 08:43 UTC, mkartashev requested changes

2024-03-04 08:43 UTC, mkartashev commented on src/java.desktop/unix/classes/sun/awt/wl/WLComponentPeer.java
> +            this.visible = v;
There still is a possibility of two consecutive `wlSetVisible(false)` calls; we need a check like this here:
```Java
if (this.visible == v) return;
```

2024-03-14 13:11 UTC, mkartashev commented on src/java.desktop/unix/classes/sun/awt/wl/WLComponentPeer.java
> +            this.visible = v;
```suggestion
            if (this.visible == v) return;
            
            this.visible = v;
```

2024-03-14 13:13 UTC, mkartashev commented on src/java.desktop/unix/classes/sun/awt/wl/WLComponentPeer.java
> +            WLToolkit.postEvent(new WindowEvent((Window) target, WindowEvent.WINDOW_CLOSING));
```suggestion
            // TODO: may need a better way of notifying interested components about popup disappearance
            WLToolkit.postEvent(new WindowEvent((Window) target, WindowEvent.WINDOW_CLOSING));
```

2024-03-14 13:16 UTC, mkartashev commented on src/java.desktop/unix/classes/sun/awt/wl/WLComponentPeer.java
> +        WLToolkit.postEvent(new WindowEvent((Window) target, WindowEvent.WINDOW_CLOSING));
```suggestion
        // TODO: may need a better way of notifying interested components about popup disappearance
        WLToolkit.postEvent(new WindowEvent((Window) target, WindowEvent.WINDOW_CLOSING));
```

2024-03-14 13:16 UTC, mkartashev commented
@xdom If you accept the edits I suggested, we can move forward with this PR.

2024-03-15 12:49 UTC, avu approved these changes
LGTM

2024-03-18 06:15 UTC, mkartashev approved these changes

2024-03-18 06:23 UTC, merged

2024-05-22 11:58 UTC, mkartashev commented
@xdom I'm now synchronizing Wayland-related work with the [project Wakefield repository](https://github.com/openjdk/wakefield/). Since this patch was contributed by you, I can't simply cherry-pick it to OpenJDK. Would you be willing to open a PR against branch `jdk21.0.1-wayland` in that repository? That is, assuming you are or can become an OpenJDK contributor?