JBR-6771 BoxLayout throws mysterious NPEs due to previous exceptions
JetBrains/JetBrainsRuntime pull request #326
Opened 2024-03-01 16:17 UTC by stachenov

This isn't really a bug, more like an inconvenience that masks real bugs.

The `checkRequests` method only does layout initialization
if it isn't initialized already. However, when an exception
is thrown during the initialization, the layout may end up
in a half-initialized state.

Fix this by using the field that is initialized the last to check
if the layout is initialized. If that field is null, it may mean
that the layout isn't initialized or that the last attempt
failed midway. Then we try again. This attempt can,
of course, break for the same reason as the previous one,
but in that case we'll at least get a stack trace pointing
to a real cause of the error and not some mysterious NPE
that seems to be impossible from the logic.

2024-03-07 08:58 UTC, mkartashev requested changes

2024-03-07 09:19 UTC, stachenov commented on test/jdk/javax/swing/BoxLayout/NPECheckRequests/NPECheckRequests.java
> +
Oops, looks like I've staged something incorrectly and haven't checked what I committed. It _was_ a working test with the proper info. I'll re-push.

2024-03-07 10:45 UTC, stachenov commented on test/jdk/javax/swing/BoxLayout/NPECheckRequests/NPECheckRequests.java
> +
Force-pushed the full version. It was indeed partially staged for some reason.

2024-03-07 11:35 UTC, mkartashev approved these changes

2024-04-15 07:44 UTC, mkartashev commented
Merged into `main`, `jbr21`, `jbr17`.

2024-04-15 07:44 UTC, closed without merging