JBR-6808 Don't create AccessibleJTreeNode for the tree root if it's not visible
JetBrains/JetBrainsRuntime pull request #336
Opened 2024-03-11 17:04 UTC by dmitrii-drobotov

This fixes an issue with `AccessibleJTreeNode#getBounds`, which adjusts the node's bounds according to the parent node:
https://github.com/JetBrains/JetBrainsRuntime/blob/ce6f4d023beef597cb670072e093eeb0fb25dfd5/src/java.desktop/share/classes/javax/swing/JTree.java#L5425-L5437

For nodes whose parent is the invisible root, `getBounds` was returning null, and it caused issues with assistive technology like macOS Accessibility Zoom.

This also matches behavior in `AccessibleJTree#getAccessibleChild` which creates accessible node for the root only if it's visible:

https://github.com/JetBrains/JetBrainsRuntime/blob/ce6f4d023beef597cb670072e093eeb0fb25dfd5/src/java.desktop/share/classes/javax/swing/JTree.java#L4541-L4575

### Before

Invisible root has an item in the hierarchy:

<img width="1420" alt="Accessibility hierarchy for JTree showing an item for the root, which is not visible in UI" src="https://github.com/JetBrains/JetBrainsRuntime/assets/102954094/1bdead3e-2b10-455c-8b56-74c83eb9077e">

In IntelliJ it caused issues with macOS Accessibility Zoom when selecting top level nodes:

https://github.com/JetBrains/JetBrainsRuntime/assets/102954094/e689c409-19a2-4341-a92d-b7b78e1a03ae

### After

No item in the hierarchy for the invisible root:

<img width="1423" alt="Screenshot 2024-03-11 at 12 20 25" src="https://github.com/JetBrains/JetBrainsRuntime/assets/102954094/619489b9-55fb-4bfa-9576-ab442b531338">

issues with macOS Accessibility Zoom when selecting top level nodes are fixed:

https://github.com/JetBrains/JetBrainsRuntime/assets/102954094/002daa88-6c8a-48d1-ad69-c27e3f67b3fd

2024-03-20 19:10 UTC, NikitkoCent requested changes
Thanks for the patch! Could you please supplement the patch with an automatic regression test? AFAIU it shouldn't be difficult in this case.

2024-03-28 11:30 UTC, dmitrii-drobotov commented
I've added the test, and also ported the change to the copy of `AccessibleJTreeNode` in AccessBridge.java. Turns out it's used instead of the normal `AccessibleJTreeNode` in case when tree is the parent of the node: https://github.com/JetBrains/JetBrainsRuntime/blob/b3cd00363f3e6022b6fb47823c0128c7f5d86798/src/jdk.accessibility/windows/classes/com/sun/java/accessibility/internal/AccessBridge.java#L5469-L5479

It passes `null` as accessible parent argument, so needs to be fixed it the same way. With this additional fix in AccessBridge, the [JDK-8249806](https://bugs.openjdk.org/browse/JDK-8249806) is completely fixed. 

Before fix:
![NVDA reads tree levels starting from 2](https://github.com/JetBrains/JetBrainsRuntime/assets/102954094/4b2e38fa-a8c3-4a35-9f88-a6984b676f5e)

After:
![NVDA reads tree levels starting from 1](https://github.com/JetBrains/JetBrainsRuntime/assets/102954094/3e457029-dec9-4455-9d25-365d235fe67c)

2024-05-08 19:46 UTC, NikitkoCent requested changes
I've tested the patch on macOS: the changes and the test look stable (reverting the changes in `src` makes the test fail immediately ; applying those changes back makes the test pass stable).

However, there's a request for a little improvement of the test.

2024-05-08 19:46 UTC, NikitkoCent commented on test/jdk/javax/accessibility/8249806/AccessibleJTreeNodeAccessibleParentTest.java
> +                jTree.getAccessibleContext().addPropertyChangeListener(evt -> {
As far as I understand, if the control flow doesn't reach the check `if (!jTree.equals(accessibleNode.getAccessibleContext().getAccessibleParent()))`, it will be also the wrong behavior, although there's no check for this here.

Could you please add such a check? 🙏

2024-05-09 12:51 UTC, dmitrii-drobotov commented on test/jdk/javax/accessibility/8249806/AccessibleJTreeNodeAccessibleParentTest.java
> +                jTree.getAccessibleContext().addPropertyChangeListener(evt -> {
Good point, I've added it.

2024-05-10 15:59 UTC, NikitkoCent approved these changes
Great! LGTM

2024-05-10 16:00 UTC, merged