IJPL-150176: extension-based filters in native file dialogs
JetBrains/JetBrainsRuntime pull request #386
Opened 2024-05-22 13:39 UTC by trespasserw

Adding an ability to set simple file-extension-based filters for file dialogs. While being less flexible than `FileDialog#setFilenameFilter`, extension-based filters don't require callbacks to Java code and are supported on all platforms.

2024-05-22 13:40 UTC, trespasserw commented
(WIP; the implementation for macOS comes later)

2024-05-22 16:18 UTC, avu commented
@trespasserw It would be nice to have a regression test for this feature (something like test/jdk/jb/javax/swing/CustomTitleBar/JFrameNativeControlsMacOSTest.java). It can be created even for incomplete implementation using the platform tag in the jtreg test case.

2024-05-23 03:08 UTC, vprovodin commented
Should the ticket IJPL-150176 be moved into the JBR YT project?

2024-05-23 05:53 UTC, trespasserw commented
@vprovodin what are those commits?

IJPL-150176 should not be moved, but I will create a companion ticket in JBR later today and edit commit messages.

2024-05-23 10:19 UTC, YaaZ requested changes

2024-05-23 10:19 UTC, YaaZ commented on src/java.desktop/share/classes/com/jetbrains/desktop/JBRFileDialog.java
> +    public void setLocalizationStrings(String openButtonText, String selectFolderButtonText, String allFilesFilterDescription) {
Removing an API method is a breaking change, I think adding more generic `setLocalizationString(key, value)` would be better

2024-05-23 10:19 UTC, YaaZ commented on src/java.desktop/share/classes/com/jetbrains/desktop/JBRFileDialog.java
> -     */
What is the purpose of removing this javadoc?

2024-05-23 10:19 UTC, YaaZ commented on src/jetbrains.api/src/com/jetbrains/JBRFileDialog.java
> +     *     neither bit set is treated as a default platform-specific behavior</li>
I think original wording was more clear and new one is kinda ambiguous:
* "both unset bits are treated as a default platform-specific behavior" -> if neither of `SELECT_FILES_HINT` or `SELECT_DIRECTORIES_HINT` is set, then behavior is platform-specific
* "neither bit set is treated as a default platform-specific behavior" -> No combination of bits will result in platform-specific behavior?

2024-05-23 11:11 UTC, trespasserw commented on src/java.desktop/share/classes/com/jetbrains/desktop/JBRFileDialog.java
> +    public void setLocalizationStrings(String openButtonText, String selectFolderButtonText, String allFilesFilterDescription) {
AFAIU, classes in `com.jetbrains.desktop` are part of the corresponding JBR module which the client code is not supposed to use directly. It is proxied by `com.jetbrains.JBRFileDialog` in `jbr-api`, which preserves compatibility.

A key-based approach is an interesting idea; I'll try.

2024-05-23 11:12 UTC, trespasserw commented on src/java.desktop/share/classes/com/jetbrains/desktop/JBRFileDialog.java
> -     */
The comments weren't removed, they were moved from a "backend" class to the "API" one.

2024-05-23 11:38 UTC, trespasserw commented on src/jetbrains.api/src/com/jetbrains/JBRFileDialog.java
> +     *     neither bit set is treated as a default platform-specific behavior</li>
Updated.

2024-05-23 12:01 UTC, YaaZ commented on src/java.desktop/share/classes/com/jetbrains/desktop/JBRFileDialog.java
> +    public void setLocalizationStrings(String openButtonText, String selectFolderButtonText, String allFilesFilterDescription) {
That's correct, but as you added default implementation for this method in`jbr-api`, means that just running on a newer JBR (without updating jbr-api dependency) would already be incompatible, as there would be no implementation for that API method. I suggest leaving this method as is, we can just mark is as deprecated for the time being

2024-05-30 16:37 UTC, YaaZ commented
Pushed to `main` for now

2024-06-05 11:12 UTC, YaaZ commented
Pushed this to `main`, `jbr17`, `jbr21`, so closing the review

2024-06-05 11:12 UTC, closed without merging