JBR-7237 Fix circular dependency of Wayland and Vulkan initialization
JetBrains/JetBrainsRuntime pull request #396
Opened 2024-05-31 23:06 UTC by YaaZ

This adds asynchronous Vulkan initialization.
1. `WLGraphicsEnvironment` starts Vulkan initialization in separate thread and proceeds with Wayland initialization
2. Before `vkGetPhysicalDeviceWaylandPresentationSupportKHR` Vulkan init waits for the `wl_display` to become available
3. `VKInstance.isVulkanEnabled()` which is used later by `WLGraphicsDevice` waits for the Vulkan initialization to finish

2024-06-02 12:50 UTC, avu commented on src/java.desktop/share/native/common/java2d/vulkan/VKBase.c
> +        while (!wl_display_initialized) {
Did you measure the performance gain from parallel initialization?

2024-06-02 12:50 UTC, avu commented on src/java.desktop/unix/native/libawt_wlawt/WLToolkit.c
> +    syscall(SYS_futex, &wl_display_initialized, FUTEX_WAKE_PRIVATE, INT_MAX, NULL, NULL, 0);
Why did you use such a kind of synchronization here?   (there is only one place in hotspot where JDK use it)

2024-06-03 07:02 UTC, mkartashev requested changes

2024-06-03 07:02 UTC, mkartashev commented on src/java.desktop/share/native/common/java2d/vulkan/VKBase.c
> +extern volatile uint32_t wl_display_initialized;
When inter-thread synchronization is spread between the native and Java worlds it becomes especially hard to follow. Maybe we can stay within Java in this instance? By the time `WLToolkit::initIDs()` exits normally (i.e. not through an exception), the connection to the Wayland server is guaranteed to exist. Possibly this synchronization point can be placed there?

2024-06-03 10:25 UTC, avu commented on src/java.desktop/share/native/common/java2d/vulkan/VKBase.c
> +extern volatile uint32_t wl_display_initialized;
Yes, that's why I asked about it. Also, we want to extend the Vulkan pipeline to windows, so it's better to have a more general synchronization mechanism.

2024-06-03 10:47 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/vulkan/VKBase.c
> +extern volatile uint32_t wl_display_initialized;
By the time `WLToolkit::initIDs()` exits normally, Vulkan should already be initialized, because it goes through `initIDs`->`notifyOutputConfigured` and creates a `WLGraphicsDevice`, which needs to know about the Vulkan support to create either `WLVKGraphicsConfig`, or `WLSMGraphicsConfig`. And Vulkan initialization needs a `wl_display` connection to query for presentation support, that's why the synchronization is placed here. This is only specific to Linux, as Windows does not depend on any external connection and therefore does not need such synchronization.

2024-06-03 10:48 UTC, YaaZ commented on src/java.desktop/unix/native/libawt_wlawt/WLToolkit.c
> +    wl_display_initialized = 1;
Yes, but Vulkan initialization may already be waiting for the `wl_display`, so we need to notify it even if Wayland initialization failed. There is a null check in Vulkan code too.

2024-06-03 10:50 UTC, YaaZ commented on src/java.desktop/unix/native/libawt_wlawt/WLToolkit.c
> +    syscall(SYS_futex, &wl_display_initialized, FUTEX_WAKE_PRIVATE, INT_MAX, NULL, NULL, 0);
IDK, I just though futex is an easy, lightweight and already available tool for the case (waiting for the variable to change).

2024-06-03 10:52 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/vulkan/VKBase.c
> +        while (!wl_display_initialized) {
I didn't because I made these changes to solve the cyclic dependency in the first place. Original solution just crashes, so I cannot measure real gain, but I can get a rough estimate.

2024-06-07 14:48 UTC, mkartashev commented on src/java.desktop/share/native/common/java2d/vulkan/VKBase.c
> +static struct wl_display *wl_display;
This name clashes with `extern struct wl_display *wl_display` declared in WLToolkit.c
Maybe rename this one with a different prefix?

2024-06-10 08:01 UTC, mkartashev approved these changes

2024-06-10 11:19 UTC, avu approved these changes
Overal, LGTM. I think we'll get rid of global data later.

2024-06-14 10:09 UTC, avu approved these changes
LGTM

2024-06-14 10:22 UTC, merged