JBR-7254 Impossible to copy/paste files in Project tree
JetBrains/JetBrainsRuntime pull request #398
Opened 2024-06-04 06:02 UTC by mkartashev

[JBR-7254](https://youtrack.jetbrains.com/issue/JBR-7254) Impossible to copy/paste files in Project tree

2024-06-06 15:12 UTC, NikitkoCent requested changes
I'm still in the process of reviewing, but have noticed that the patch doesn't work for multiple selected files, unlike under XToolkit or on macOS (haven't tested with Windows).

2024-06-07 11:56 UTC, NikitkoCent commented on src/java.desktop/unix/classes/sun/awt/wl/WLDataTransferer.java
> +        }
I'm astonished that X, Windows and macOS toolkits do some scary native calls here, and we're like "Hey, it's just char arrays delimited by \n!" :smile: :fire:

2024-06-11 10:24 UTC, mkartashev commented
> I'm still in the process of reviewing, but have noticed that the patch doesn't work for multiple selected files, unlike under XToolkit or on macOS (haven't tested with Windows).

Does it work for you under XToolkit when you copy a group of files from outside of IDEA, like from a file manager? It doesn't for me. When you copy within IDEA, it doesn't really go through the clipboard, there's a shortcut that can't be used with Wayland, in which case it will likely remain a limitation of WLToolkit for the foreseeable future. I will, nonetheless, look into this further.

BTW, copying a group of files from IDEA to a file manager works both with WLToolkit and XToolkit.

2024-06-11 14:03 UTC, mkartashev commented
Copying of group of files has been fixed; the problem was the delimiter character: in encoding, `\0` was used, while decoding was done using `\n`. 
This, however, doesn't *always* work for *some* projects in IDEA. Seems like some work is needed on the IDEA side as well after this has been merged.

2024-06-12 16:04 UTC, NikitkoCent commented
> Copying of group of files has been fixed; the problem was the delimiter character: in encoding, `\0` was used, while decoding was done using `\n`. This, however, doesn't _always_ work for _some_ projects in IDEA.

Pasting two empty files copied from one directory to another within the same empty project doesn't work on my side. However, I can paste those files through the Gnome file manager. Here're the logs.
```
2024-06-12 17:57:22,074 [  16313]   FINE - sun.awt.wl.WLClipboard - Clipboard: About to offer new contents using Wayland event serial 8079
2024-06-12 17:57:22,075 [  16314]   FINE - sun.awt.wl.WLClipboard - Clipboard: New one is available in these integer formats: [3, 2, 4, 18, 0, 20, 21, 22, 23, 1, 17, 16, 10, 11, 12, 13, 14, 15, 9]
2024-06-12 17:57:22,075 [  16314]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 3 -> UTF8_STRING
2024-06-12 17:57:22,075 [  16314]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 2 -> TEXT
2024-06-12 17:57:22,075 [  16314]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 4 -> STRING
2024-06-12 17:57:22,075 [  16314]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 18 -> text/plain;charset=UTF-16
2024-06-12 17:57:22,075 [  16314]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 0 -> text/plain;charset=utf-8
2024-06-12 17:57:22,075 [  16314]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 20 -> text/plain;charset=UTF-16BE
2024-06-12 17:57:22,075 [  16314]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 21 -> text/plain;charset=UTF-16LE
2024-06-12 17:57:22,075 [  16314]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 22 -> text/plain;charset=ISO-8859-1
2024-06-12 17:57:22,075 [  16314]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 23 -> text/plain;charset=US-ASCII
2024-06-12 17:57:22,075 [  16314]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 1 -> text/plain
2024-06-12 17:57:22,075 [  16314]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 17 -> FILE_NAME
2024-06-12 17:57:22,075 [  16314]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 16 -> text/uri-list
2024-06-12 17:57:22,075 [  16314]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 10 -> text/uri-list;charset=UTF-16
2024-06-12 17:57:22,075 [  16314]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 11 -> text/uri-list;charset=UTF-8
2024-06-12 17:57:22,075 [  16314]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 12 -> text/uri-list;charset=UTF-16BE
2024-06-12 17:57:22,075 [  16314]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 13 -> text/uri-list;charset=UTF-16LE
2024-06-12 17:57:22,075 [  16314]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 14 -> text/uri-list;charset=ISO-8859-1
2024-06-12 17:57:22,075 [  16314]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 15 -> text/uri-list;charset=US-ASCII
2024-06-12 17:57:22,075 [  16314]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 9 -> x-special/gnome-copied-files
2024-06-12 17:57:22,075 [  16314]   FINE - sun.awt.wl.WLClipboard - Clipboard: Offering new contents (com.intellij.ide.PsiCopyPasteManager$MyTransferable@59707814) in these MIME formats: [UTF8_STRING, TEXT, STRING, text/plain;charset=UTF-16, text/plain;charset=utf-8, text/plain;charset=UTF-16BE, text/plain;charset=UTF-16LE, text/plain;charset=ISO-8859-1, text/plain;charset=US-ASCII, text/plain, FILE_NAME, text/uri-list, text/uri-list;charset=UTF-16, text/uri-list;charset=UTF-8, text/uri-list;charset=UTF-16BE, text/uri-list;charset=UTF-16LE, text/uri-list;charset=ISO-8859-1, text/uri-list;charset=US-ASCII, x-special/gnome-copied-files]
2024-06-12 17:57:22,076 [  16315]   FINE - sun.awt.wl.WLClipboard - Clipboard: will write contents (com.intellij.ide.PsiCopyPasteManager$MyTransferable@59707814) in format text/plain;charset=utf-8 to fd=204
2024-06-12 17:57:22,077 [  16316]   FINE - sun.awt.wl.WLClipboard - Clipboard: data flavor: java.awt.datatransfer.DataFlavor[mimetype=application/x-java-serialized-object;representationclass=java.lang.String]
2024-06-12 17:57:22,077 [  16316]   FINE - sun.awt.wl.WLClipboard - Clipboard: about to write 11 bytes to java.io.FileOutputStream@8968c27
2024-06-12 17:57:22,085 [  16324]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 94740103347296: x-special/gnome-copied-files
2024-06-12 17:57:22,085 [  16324]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 94740103347296: text/uri-list;charset=US-ASCII
2024-06-12 17:57:22,085 [  16324]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 94740103347296: text/uri-list;charset=ISO-8859-1
2024-06-12 17:57:22,085 [  16324]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 94740103347296: text/uri-list;charset=UTF-16LE
2024-06-12 17:57:22,085 [  16324]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 94740103347296: text/uri-list;charset=UTF-16BE
2024-06-12 17:57:22,085 [  16324]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 94740103347296: text/uri-list;charset=UTF-8
2024-06-12 17:57:22,085 [  16324]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 94740103347296: text/uri-list;charset=UTF-16
2024-06-12 17:57:22,085 [  16324]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 94740103347296: text/uri-list
2024-06-12 17:57:22,085 [  16324]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 94740103347296: FILE_NAME
2024-06-12 17:57:22,085 [  16324]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 94740103347296: text/plain
2024-06-12 17:57:22,085 [  16324]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 94740103347296: text/plain;charset=US-ASCII
2024-06-12 17:57:22,085 [  16324]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 94740103347296: text/plain;charset=ISO-8859-1
2024-06-12 17:57:22,085 [  16324]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 94740103347296: text/plain;charset=UTF-16LE
2024-06-12 17:57:22,085 [  16324]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 94740103347296: text/plain;charset=UTF-16BE
2024-06-12 17:57:22,085 [  16324]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 94740103347296: text/plain;charset=utf-8
2024-06-12 17:57:22,085 [  16324]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 94740103347296: text/plain;charset=UTF-16
2024-06-12 17:57:22,085 [  16324]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 94740103347296: STRING
2024-06-12 17:57:22,085 [  16324]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 94740103347296: TEXT
2024-06-12 17:57:22,085 [  16324]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 94740103347296: UTF8_STRING
2024-06-12 17:57:22,085 [  16324]   FINE - sun.awt.wl.WLClipboard - Clipboard: Lost ownership of our clipboard
2024-06-12 17:57:22,085 [  16324]   FINE - sun.awt.wl.WLClipboard - Clipboard: new clipboard is available: 94740103347296
2024-06-12 17:57:22,360 [  16599]   INFO - #o.j.j.b.i.CompilerReferenceIndex - backward reference index version doesn't exist
2024-06-12 17:57:22,365 [  16604]   INFO - #c.i.c.b.IsUpToDateCheckStartupActivity - suitable consumer is not found
2024-06-12 17:57:22,392 [  16631]   INFO - #c.i.w.i.i.GlobalWorkspaceModel - Sync global entities with mutable entity storage
2024-06-12 17:57:22,396 [  16635]   INFO - #c.i.w.i.i.j.s.JpsProjectModelSynchronizer - Attempt 1: Apply JPS storage (iml files)
2024-06-12 17:57:22,429 [  16668]   INFO - #c.i.w.i.i.EntitiesOrphanageImpl - Update orphanage. 0 modules added
2024-06-12 17:57:22,431 [  16670]   INFO - #c.i.w.i.i.j.s.JpsProjectModelSynchroniz [...]

2024-06-12 16:11 UTC, NikitkoCent commented
Pasting of multiple files copied from outside of the IDE works well though. As far as I understand from the logs, copying within IDE writes the files list to the clipboard as plain text instead of an uri list (or smth else?)

2024-06-13 10:36 UTC, mkartashev commented
> Pasting two empty files copied from one directory to another within the same empty project doesn't work on my side.

Are you sure you have the latest commit? This scenario started working on my side with the recent changes.
[Screencast from 13-06-24 14:35:17.webm](https://github.com/JetBrains/JetBrainsRuntime/assets/28651297/d1387aef-d375-44a7-a82c-15a240dea64e)

2024-06-13 20:22 UTC, NikitkoCent commented
> > Pasting two empty files copied from one directory to another within the same empty project doesn't work on my side.
> 
> Are you sure you have the latest commit? This scenario started working on my side with the recent changes. [Screencast from 13-06-24 14:35:17.webm](https://github.com/JetBrains/JetBrainsRuntime/assets/28651297/d1387aef-d375-44a7-a82c-15a240dea64e)

Ok, I confirm it works in PyCharm Nightly, but does **not** work in IDEA Nightly (e.g. today's build).
Double checked everything, even built your branch in a new separate worktree.

2024-06-14 06:05 UTC, mkartashev commented
If the "Paste" dialog does not appear, you may be experiencing [JBR-7290](https://youtrack.jetbrains.com/issue/JBR-7290). Could you please re-try with a workaround for that issue (`-Dswing.bufferPerWindow=false`)? I was not able to reproduce the pasting problem with IDEA (built on June 13) either, short of experiencing JBR-7290 occasionally.

2024-06-18 02:38 UTC, NikitkoCent commented
@mkartashev,
Unfortunately, neither the workaround `-Dswing.bufferPerWindow=false` nor the fix of JBR-7290 has helped. Here's the logs from PyCharm, which doesn't have this issue:
```
2024-06-18 04:30:00,552 [ 212007]   FINE - sun.awt.wl.WLClipboard - Clipboard: About to offer new contents using Wayland event serial 54900
2024-06-18 04:30:00,553 [ 212008]   FINE - sun.awt.wl.WLClipboard - Clipboard: New one is available in these integer formats: [1, 2, 3, 13, 0, 15, 16, 17, 18, 19, 12, 11, 5, 6, 7, 8, 9, 10, 4]
2024-06-18 04:30:00,553 [ 212008]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 1 -> UTF8_STRING
2024-06-18 04:30:00,553 [ 212008]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 2 -> TEXT
2024-06-18 04:30:00,553 [ 212008]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 3 -> STRING
2024-06-18 04:30:00,553 [ 212008]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 13 -> text/plain;charset=UTF-16
2024-06-18 04:30:00,553 [ 212008]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 0 -> text/plain;charset=utf-8
2024-06-18 04:30:00,553 [ 212008]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 15 -> text/plain;charset=UTF-16BE
2024-06-18 04:30:00,553 [ 212008]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 16 -> text/plain;charset=UTF-16LE
2024-06-18 04:30:00,553 [ 212008]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 17 -> text/plain;charset=ISO-8859-1
2024-06-18 04:30:00,553 [ 212008]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 18 -> text/plain;charset=US-ASCII
2024-06-18 04:30:00,553 [ 212008]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 19 -> text/plain
2024-06-18 04:30:00,553 [ 212008]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 12 -> FILE_NAME
2024-06-18 04:30:00,553 [ 212008]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 11 -> text/uri-list
2024-06-18 04:30:00,553 [ 212008]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 5 -> text/uri-list;charset=UTF-16
2024-06-18 04:30:00,553 [ 212008]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 6 -> text/uri-list;charset=UTF-8
2024-06-18 04:30:00,553 [ 212008]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 7 -> text/uri-list;charset=UTF-16BE
2024-06-18 04:30:00,553 [ 212008]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 8 -> text/uri-list;charset=UTF-16LE
2024-06-18 04:30:00,553 [ 212008]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 9 -> text/uri-list;charset=ISO-8859-1
2024-06-18 04:30:00,553 [ 212008]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 10 -> text/uri-list;charset=US-ASCII
2024-06-18 04:30:00,553 [ 212008]   FINE - sun.awt.wl.WLClipboard - Clipboard: formats mapping 4 -> x-special/gnome-copied-files
2024-06-18 04:30:00,553 [ 212008]   FINE - sun.awt.wl.WLClipboard - Clipboard: Offering new contents (com.intellij.ide.PsiCopyPasteManager$MyTransferable@f7a39b3) in these MIME formats: [UTF8_STRING, TEXT, STRING, text/plain;charset=UTF-16, text/plain;charset=utf-8, text/plain;charset=UTF-16BE, text/plain;charset=UTF-16LE, text/plain;charset=ISO-8859-1, text/plain;charset=US-ASCII, text/plain, FILE_NAME, text/uri-list, text/uri-list;charset=UTF-16, text/uri-list;charset=UTF-8, text/uri-list;charset=UTF-16BE, text/uri-list;charset=UTF-16LE, text/uri-list;charset=ISO-8859-1, text/uri-list;charset=US-ASCII, x-special/gnome-copied-files]
2024-06-18 04:30:00,554 [ 212009]   FINE - sun.awt.wl.WLClipboard - Clipboard: will write contents (com.intellij.ide.PsiCopyPasteManager$MyTransferable@f7a39b3) in format text/plain;charset=utf-8 to fd=185
2024-06-18 04:30:00,554 [ 212009]   FINE - sun.awt.wl.WLClipboard - Clipboard: data flavor: java.awt.datatransfer.DataFlavor[mimetype=application/x-java-serialized-object;representationclass=java.lang.String]
2024-06-18 04:30:00,554 [ 212009]   FINE - sun.awt.wl.WLClipboard - Clipboard: about to write 11 bytes to java.io.FileOutputStream@7e2972a3
2024-06-18 04:30:00,563 [ 212018]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 93945361639392: x-special/gnome-copied-files
2024-06-18 04:30:00,564 [ 212019]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 93945361639392: text/uri-list;charset=US-ASCII
2024-06-18 04:30:00,564 [ 212019]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 93945361639392: text/uri-list;charset=ISO-8859-1
2024-06-18 04:30:00,564 [ 212019]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 93945361639392: text/uri-list;charset=UTF-16LE
2024-06-18 04:30:00,564 [ 212019]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 93945361639392: text/uri-list;charset=UTF-16BE
2024-06-18 04:30:00,564 [ 212019]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 93945361639392: text/uri-list;charset=UTF-8
2024-06-18 04:30:00,564 [ 212019]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 93945361639392: text/uri-list;charset=UTF-16
2024-06-18 04:30:00,564 [ 212019]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 93945361639392: text/uri-list
2024-06-18 04:30:00,564 [ 212019]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 93945361639392: FILE_NAME
2024-06-18 04:30:00,564 [ 212019]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 93945361639392: text/plain
2024-06-18 04:30:00,564 [ 212019]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 93945361639392: text/plain;charset=US-ASCII
2024-06-18 04:30:00,564 [ 212019]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 93945361639392: text/plain;charset=ISO-8859-1
2024-06-18 04:30:00,564 [ 212019]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 93945361639392: text/plain;charset=UTF-16LE
2024-06-18 04:30:00,564 [ 212019]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 93945361639392: text/plain;charset=UTF-16BE
2024-06-18 04:30:00,564 [ 212019]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 93945361639392: text/plain;charset=utf-8
2024-06-18 04:30:00,564 [ 212019]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 93945361639392: text/plain;charset=UTF-16
2024-06-18 04:30:00,564 [ 212019]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 93945361639392: STRING
2024-06-18 04:30:00,564 [ 212019]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 93945361639392: TEXT
2024-06-18 04:30:00,564 [ 212019]   FINE - sun.awt.wl.WLClipboard - Clipboard: new format is available for 93945361639392: UTF8_STRING
2024-06-18 04:30:00,564 [ 212019]   FINE - sun.awt.wl.WLClipboard - Clipboard: Lost ownership of our clipboard
2024-06-18 04:30:00,564 [ 212019]   FINE - sun.awt.wl.WLClipboard - Clipboard: new clipboard is available: 93945361639392
2024-06-18 04:30:02,153 [ 213608]   INFO - #c.i.d.u.SqlDialects - SQL dialects initialized in 8 ms
2024-06-18 04:30:03,963 [ 215418]   FINE - sun.awt.wl.WLClipboard - Clipboard: requested content of clipboard with handle 93945361639392 in format 7
2024-06-18 04:30:03,963 [ 215418]   FINE - sun.awt.wl.WLClipboard - Clipboard: will read data from 186 in format text/uri-list;charset=UTF-16BE
2024-06-18 04:30:03,964 [ 215419]   FINE - sun.awt.wl.WLClipboard - Clipboard: will write contents (com.intellij.ide.PsiCopyPasteManager$MyTransferable@f7a39b3) in format text/uri-list;charset=UTF-16BE to fd=187
2024-06-18 04:30:03,964 [ 215419]   FINE - sun.awt.wl.WLClipboard - Clipboard: data flavor: java.awt.datatransfer.DataFlavor[mimetype=text/uri-list;representationclass=java.lang.String]
2024-06-18 04:30:03,964 [ 215419]   FINE - sun.awt.wl.WLClipboard - Clipboard: about to write 107 bytes to java.io.FileOutputStream@7a16e9be
2024 [...]

2024-06-18 09:59 UTC, NikitkoCent commented
After some digging of the IntelliJ platform, I've got more details of how to reproduce the issue.
You need to select a few files in a way that _**the last chosen file doesn't have any extension**_ (so it's a file without a dot in the name). E.g. the bug can be reproduced if the copied files had been selected in the following order:
```
MyJavaClass.java
file
```
And can't be reproduced if the files had been selected in the opposite order:
```
file
MyJavaClass.java
```

Moreover now I think that the issue should be fixed on the IntelliJ side, not in JBR. Thus there's nothing more to do about the patch, so LGTM (and file a separate issue about the problem).

2024-06-18 09:59 UTC, NikitkoCent approved these changes

2024-06-18 10:04 UTC, merged

2024-06-18 10:30 UTC, mkartashev commented
A separate issue was filed to track the remaining problem:
[IJPL-156798](https://youtrack.jetbrains.com/issue/IJPL-156798) Wayland: cannot paste a group of files with no extension