JBR-7481: Work around for mouse entered/exited events
JetBrains/JetBrainsRuntime pull request #434
Opened 2024-08-12 09:02 UTC by stachenov

Implement a workaround for the bug when mouse entered/exited events are not generated by AppKit for whatever reason. Needed for the cursor set using `setCursor` to be respected, as it relies on `sun.lwawt.LWWindowPeer#getPeerUnderCursor`, which is updated according to mouse events. If it's wrong, the cursor is also wrong. See the YT issue for details:

https://youtrack.jetbrains.com/issue/JBR-7481

2024-09-02 03:15 UTC, NikitkoCent requested changes
Thank you for the patch! I've tested it and found no problems, however there's 1 question

2024-09-02 03:15 UTC, NikitkoCent commented on src/java.desktop/macosx/classes/sun/lwawt/MouseEnteredExitedBugWorkaround.java
> +class MouseEnteredExitedBugWorkaround {
Was there a reason to split the workaround's logic between `Jbr7481MouseEnteredExitedFix` and `MouseEnteredExitedBugWorkaround`? I feel like keeping everything in `Jbr7481MouseEnteredExitedFix` is better from the responsibility point of view - currently it's not obvious which problem `MouseEnteredExitedBugWorkaround` solves and what it belongs to (ofc until you start exploring and git-blaming the code)

2024-09-02 06:45 UTC, stachenov commented on src/java.desktop/macosx/classes/sun/lwawt/MouseEnteredExitedBugWorkaround.java
> +class MouseEnteredExitedBugWorkaround {
Makes sense. Updated and force-pushed.

2024-09-04 11:42 UTC, NikitkoCent commented
Looks good. I'll merge it into `main` and wait for the post-commit testing results. If they're fine, the patch will also be delivered to `jbr17` and `jbr21`. Until then let's keep the PR open (so that I won't forget to finish all the work).

2024-09-04 11:43 UTC, NikitkoCent approved these changes

2024-09-05 12:37 UTC, closed without merging