JBR-7456 add regression test checking if implementations of all available the random number generator algorithms can be instantiated  including the deafult one
JetBrains/JetBrainsRuntime pull request #444
Opened 2024-08-21 11:09 UTC by vprovodin

2024-08-21 12:21 UTC, mkartashev commented on test/jdk/jb/java/util/RandomGeneratorTest.java
> +}
This is an extra `}` with no corresponding '{'

2024-08-21 12:22 UTC, mkartashev commented on test/jdk/jb/java/util/RandomGeneratorTest.java
> +import java.util.Comparator;
It's best to have a copyright header even if we won't contribute this file to OpenJDK

2024-08-21 12:23 UTC, mkartashev commented on test/jdk/jb/java/util/RandomGeneratorTest.java
> +public static void main(final String[] args) throws Exception {
Implicitly declared classes require an extra compiler option; will jtreg work with this test?

2024-08-21 12:23 UTC, mkartashev commented on test/jdk/jb/java/util/RandomGeneratorTest.java
> +    if (isFailed)
There are many undeclared variables in the test such as `isFailed` and others.

2024-08-21 12:25 UTC, mkartashev commented on test/jdk/jb/java/util/RandomGeneratorTest.java
> +        RandomGenerator randomGenerator = factory.create();System.out.printf("%s %s - ",
Need a line break after `;` in this line

2024-08-21 23:29 UTC, vprovodin commented
Sorry, the test was developed&tested in one branch, but pr was submitted from another by mistake
All notes were fixed

2024-08-22 08:27 UTC, mkartashev requested changes

2024-08-22 08:27 UTC, mkartashev commented on test/jdk/jb/java/util/RandomGeneratorTest.java
> +            RandomGenerator randomGenerator = factory.create();System.out.printf("%s %s - ",
Still need a line break after `;` in this line.

2024-08-22 08:27 UTC, mkartashev commented on test/jdk/jb/java/util/RandomGeneratorTest.java
> + * Copyright (c) 2024,  JetBrains s.r.o.
There's no need for `, ` in this line

2024-08-23 08:06 UTC, mkartashev approved these changes

2024-08-23 08:23 UTC, merged