Vulkan update
JetBrains/JetBrainsRuntime pull request #447
Opened 2024-08-22 00:25 UTC by YaaZ

- Fixed all validation errors.
- Added proper synchronization and image layout transitions.
- Refactored VKRenderer to hold per-device rendering context. Added per-surface render pass contexts.
- Isolated surface rendering contexts to minimize state changes. Now rendering commands are recorded per-surface.
- Added batching where possible: per-rq-flush commands, per-surface drawing commands, swapchain presentation, pipeline creation.
- Added logic for tracking and reusing arbitrary resources. Implemented for command buffers and semaphores.
- Fixed surface resize, refactored surface initialization to be robust to event order and allow delayed swapchain creation.
- Added proper choice of sRGB surface formats and spec-conformant sRGB->linear conversion for colors coming from Java.
- Added on-demand pipeline creation for actual surface formats.
- Added VK_KHR_dynamic_rendering for dynamic render pass parameters - clear, view format, multisampling(?).
- Added missing destruction logic across all Vulkan code.
- Added macros for easy checking of return codes, logging with source code location.
- Added lazy implicit initialization for dynamic arrays. Implemented ring buffer.
- Moved implementation details out of headers where possible. Stripped dead code.

2024-08-22 08:44 UTC, bourgesl commented
Will review it tomorrow

2024-08-22 13:08 UTC, mkartashev approved these changes

2024-08-22 13:08 UTC, mkartashev commented on src/java.desktop/unix/classes/sun/java2d/vulkan/WLVKSurfaceData.java
> +            buf.putInt(width / scale); // TODO This is incorrect, but we'll deal with this later, we probably need to do something on Wayland side for app-controlled scaling
Yes, it doesn't seem to be correct even now. At, say, 2x the resulting buffer will be equal to the Java client size, but will be scaled (with wp_viewport) twice its size. Not sure how that will look or even work.

2024-08-22 13:08 UTC, mkartashev commented on src/java.desktop/unix/classes/sun/java2d/vulkan/WLVKSurfaceData.java
> +            buf.putInt(width / scale); // TODO This is incorrect, but we'll deal with this later, we probably need to do something on Wayland side for app-controlled scaling
I'd prefer scale to be dropped from Vulkan code completely and only added if found absolutely necessary later.

2024-08-22 13:08 UTC, mkartashev commented on src/java.desktop/unix/native/common/java2d/vulkan/WLVKSurfaceData.c
> +    if (wl_surface != NULL) {
Should something be done when `wl_surface` is `NULL` meaning that we are about to hide the window?

2024-08-22 13:19 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/vulkan/VKBase.c
> +    raise(SIGABRT);
I used `SIGABRT` because it also causes debugger to pause at this point, which is convenient for development. Will `JNU_RUNTIME_ASSERT` behave the same?

2024-08-22 13:48 UTC, YaaZ commented on src/java.desktop/share/classes/sun/java2d/vulkan/VKRenderQueue.java
>              needsFlush = true;
Not sure this is accurate. The method itself is `synchronized`, so there is no race with concurrent flush. Next thing after `needsFlush = true;` it does is `notify();`, which will wake queue flusher thread waiting on `wait(100);`, and reading `needsFlush` after that. This guarantees visibility for the queue flusher thread.

2024-08-22 13:51 UTC, YaaZ commented on src/java.desktop/share/classes/sun/java2d/vulkan/VKSurfaceData.java
> +    protected int scale;
I agree that we shouldn't bother ourselves with scale there. But for now this is required for a workaround in `configure()`. Let's wait until we fix this and then we'll get rid of scale.

2024-08-22 14:00 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/vulkan/VKBase.c
> +        VkQueueFamilyProperties queueFamilies[queueFamilyCount];
Strictly speaking, yes. AFAIU [current OpenJDK standard is C11](https://bugs.openjdk.org/browse/JDK-8292008), where variable length arrays are optional. But I believe like it may not be a problem in practice. Personally I don't like staying away from neat language features like that, because they are optional. So I suggest to keep it like that for now and refactor it into dynamic allocation later, if we actually encounter build problems with it. If you are OK with that, of course.

2024-08-22 14:05 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/vulkan/VKRenderQueue.c
> +#define SKIP_BYTES(buf, numbytes) (buf) = ((unsigned char*)buf) + (numbytes)
No idea, I just moved this code from `VKRenderQueue.h`, which was also copy-pasted from OGL code, I guess.

2024-08-22 14:07 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/vulkan/VKRenderQueue.c
> +                VKRenderer_FillRect(&context, x, y, w, h);
Yes, `VKRenderQueue_flushBuffer` is only executed from dedicated queue flusher thread, see `VKRenderQueue.java`. I think comment would be enough.

2024-08-22 14:07 UTC, mkartashev commented on src/java.desktop/share/native/common/java2d/vulkan/VKRenderQueue.c
> +#define SKIP_BYTES(buf, numbytes) (buf) = ((unsigned char*)buf) + (numbytes)
Let's add the cast to all macros to be safe and wrap `buf` in braces in this one.

2024-08-22 14:10 UTC, YaaZ commented on src/java.desktop/unix/classes/sun/java2d/vulkan/WLVKSurfaceData.java
> +            buf.putInt(width / scale); // TODO This is incorrect, but we'll deal with this later, we probably need to do something on Wayland side for app-controlled scaling
Agree, as I said earlier, we can get rid of the scale when we fix this place and remove the workaround.
Currently, only dividing size by scale gives visually correct surface size, which is wrong, but I don't know the solution yet.

2024-08-22 14:10 UTC, mkartashev commented on src/java.desktop/share/native/common/java2d/vulkan/VKBase.c
> +        VkQueueFamilyProperties queueFamilies[queueFamilyCount];
OK, let's give our luck a test

2024-08-22 14:12 UTC, mkartashev commented on src/java.desktop/unix/classes/sun/java2d/vulkan/WLVKSurfaceData.java
> +            buf.putInt(width / scale); // TODO This is incorrect, but we'll deal with this later, we probably need to do something on Wayland side for app-controlled scaling
OK, let's postpone this one also

2024-08-22 14:14 UTC, YaaZ commented on src/java.desktop/unix/native/common/java2d/vulkan/WLVKSurfaceData.c
> +    if (wl_surface != NULL) {
No, we already called `VKSD_ResetSurface` earlier, which released all resources and reset surface to initial state.

2024-08-22 15:36 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/vulkan/VKRenderQueue.c
> +#define SKIP_BYTES(buf, numbytes) (buf) = ((unsigned char*)buf) + (numbytes)
Seems it wasn't cast in `NEXT_VAL` purposefully:
```
VKRenderQueue.c:44:64: error: lvalue required as left operand of assignment
   44 | #define NEXT_VAL(buf, type) (((type *)(((unsigned char*)(buf)) += sizeof(type)))[-1])
```

2024-08-22 16:12 UTC, YaaZ commented
OOM strategy implemented as follows:
- `ARRAY_ALLOC` returns NULL on failure
- Other macros which may cause allocation call `VK_UNHANDLED_ERROR()` on failure
- Some of these macros has "ARRAY_TRY_*" counterparts, which keep previous state on failure
- `malloc` and `calloc` calls are checked with `VK_RUNTIME_ASSERT()`

2024-08-23 08:23 UTC, mkartashev commented on src/java.desktop/share/native/common/java2d/vulkan/VKRenderQueue.c
> +#define SKIP_BYTES(buf, numbytes) (buf) = ((unsigned char*)buf) + (numbytes)
This can be defined differently such that if `buf` is not `char*`, we're going to get a complaint from the compiler instead of silently getting the wrong code should `buf` be ever (incorrectly) defined as `int*`, for example.
```
#define NEXT_VAL(buf, type) (((type *)((buf) = ((char*)(buf)) + sizeof(type)))[-1])
```

Here, 
```
  5     int *p;                                                                                         
  6     NEXT_VAL(p, short);                                                                             
```
and we're going to get
```
❯ gcc -std=c11 a.c
a.c: In function ‘main’:
a.c:1:46: warning: assignment to ‘int *’ from incompatible pointer type ‘char *’ [-Wincompatible-pointer-types]
    1 | #define NEXT_VAL(buf, type) (((type *)((buf) = ((char*)(buf)) + sizeof(type)))[-1])
      |                                              ^
a.c:6:5: note: in expansion of macro ‘NEXT_VAL’
    6 |     NEXT_VAL(p, short);
      |     ^~~~~~~~
```

2024-08-23 09:14 UTC, mkartashev approved these changes

2024-08-26 16:27 UTC, YaaZ commented on src/java.desktop/share/classes/sun/java2d/vulkan/VKSurfaceData.java
> +    // See also VKUtil_DecodeJavaColor.
It's not what you think. This parameter controls, how `Color` you have set in your `Graphics2D` is packed into integer and passed to the native Vulkan renderer. When we use pre-multiplied alpha, we multiply colors by alpha and then pack each into single byte, therefore precision loss. Moreover in Vulkan we need to convert it from sRGB to linear color space, which requires straight alpha. So this variant not only improves precision, but also removes redundant conversions. Further in Vulkan we work only with pre-multiplied alpha.

2024-08-26 16:30 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/vulkan/VKUtil.h
> +// When using this macro, make sure to leave sufficient info in the log to track failing configurations.
I thought about it, but there are usages, like resource reuse delay, which are called frequently and would spam the log, so I decided to leave logging decision to the user.

2024-08-27 10:08 UTC, mkartashev commented on src/java.desktop/share/native/common/java2d/vulkan/VKUtil.h
> +// When using this macro, make sure to leave sufficient info in the log to track failing configurations.
OK, let's see how this works out in the real world.

2024-08-27 18:23 UTC, avu commented
Concerning dynamic rendering, did you check what particular hardware does not support it? For example, this feature is available only in  470.62.07 NVidia drivers.

2024-08-27 18:56 UTC, avu commented
Please have a look at this link https://vulkan.gpuinfo.org/listdevicescoverage.php?extension=VK_KHR_dynamic_rendering
Looks like the support for this extension may not be present in some user hardware, so I think we should remove support for dynamic rendering from this pull request. It can be added later as possible optimisation.

2024-08-27 18:56 UTC, avu requested changes

2024-08-27 18:56 UTC, avu commented on src/java.desktop/share/native/common/java2d/vulkan/CArrayUtil.h
> +if ((P) != NULL) {         \
Not sure that we need to assign NULL to the pointer. It looks counter-intuitive.

2024-08-27 19:00 UTC, YaaZ commented
@avu I just checked the statistics:
https://vulkan.gpuinfo.org/displayextensiondetail.php?extension=VK_KHR_dynamic_rendering
On Linux it's 47%, which means "well supported on modern HW/drivers"

And this extension is optional, we can work with core render passes as well. I well tested both configurations.

The neccesity for this extension is motivated by dynamic nature of our J2D rendering. We can dynamically specify render pass parameters, like clearing op, which can not be known in advance, as well as removing the need to create separate render pass and framebuffer instances.

2024-08-27 19:06 UTC, YaaZ commented
The same thing with VK_EXT_extended_dynamic_state3: without it we need to compile pipelines multiple times for each alpha composite mode, and this also implies changing pipelines when composite mode is changed. With dynamic states we need much less pipelines and state changes, which is good. But both scenarios are supported and tested, of course.

2024-08-27 19:26 UTC, YaaZ commented
If you are concerned about the increased code complexity these extensions bring, it's in fact very small.
Dynamic rendering and blending extensions are meant to replace heavy and verbose core concepts with simpler yet more effective ones. Therefore main burden comes not from supporting the optional extensions, but supporting the default implementation.
You can Ctrl+F the "dynamicRendering" and "dynamicBlending" and see it yourself: if we remove these extensions, we would literally get rid of around 25 lines of code for each extension, and also get us rid of more optimal paths of execution.

2024-08-28 11:48 UTC, YaaZ commented
I split the changes into multiple smaller reviews, so I'm closing this one.
See https://github.com/JetBrains/JetBrainsRuntime/pull/452

2024-08-28 11:48 UTC, closed without merging