JBR-5973 Vulkan update
JetBrains/JetBrainsRuntime pull request #452
Opened 2024-08-28 11:44 UTC by YaaZ

- Fixed all validation errors.
- Added proper synchronization and image layout transitions.
- Refactored VKRenderer to hold per-device rendering context. Isolated surface rendering contexts.
- Implemented reusing of command buffers and semaphores
- Fixed surface resize, made surface initialization more robust.
- Added on-demand pipeline creation for actual surface formats.
- Added missing destruction logic.
- Added macros for easy checking of return codes, logging with source code location.

2024-08-28 11:45 UTC, YaaZ commented
Please disregard the first commit, there is a separate review for it: https://github.com/JetBrains/JetBrainsRuntime/pull/451

2024-08-28 11:47 UTC, bourgesl commented
No problem, this PR is obsolete as you are making ndw PRs for smaller steps...

2024-08-28 11:49 UTC, YaaZ commented
Nope, this one is not obsolete, it's a new one with smaller subset of changes.

2024-08-29 06:48 UTC, avu requested changes

2024-08-29 06:48 UTC, avu commented on src/java.desktop/share/native/common/java2d/vulkan/VKTexturePool.c
> +    VKImage* texture = VKImage_Create((VKDevice*)device, (VkExtent2D) {width, height},
I don't see any benefits by passing the VkExtent2D structure instead of width and height.

2024-08-29 06:48 UTC, avu commented on src/java.desktop/share/native/common/java2d/vulkan/VKRenderQueue.c
> +        VKRenderer_Flush(ge->devices[i].renderer);
Why do we want to use multiple devices simultaneously?

2024-08-29 06:48 UTC, avu commented on src/java.desktop/share/native/common/java2d/vulkan/VKRenderer.c
> -void VKRenderer_TextureRender(VKDevice* device, VKImage *destImage, VKImage *srcImage,
Could you please return the texture renderer? I'm using it in my image rendering work.

2024-08-29 07:01 UTC, bourgesl requested changes
Will go on my review today & tomorrow...

2024-08-29 07:01 UTC, bourgesl commented on src/java.desktop/share/native/common/java2d/vulkan/VKTypes.h
>  #define STRUCT(NAME) typedef struct NAME NAME
Sorry I do not like not reading explicit struct declaration as I did in AccelTexturePool.

2024-08-29 07:16 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/vulkan/VKRenderQueue.c
> +        VKRenderer_Flush(ge->devices[i].renderer);
Current use case is that we can be in the middle of device switch, when we have some work to finish for the old device, but already started recording commands for the new one.
But in general, architecture-wise, we are not restricted by a single "current" device, so this is a generalization.

2024-08-29 07:18 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/vulkan/VKRenderer.c
> -void VKRenderer_TextureRender(VKDevice* device, VKImage *destImage, VKImage *srcImage,
Can we return it after a few more patches? I removed it because it became unused after refactoring, but would like to bring it back in VKPipelines.

2024-08-29 07:23 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/vulkan/VKTypes.h
> +    VkClearValue vkClearValue;
It's a union. We use r, g, b, a fields for our convenience and vkClearValue for easy passing of this value to Vulkan, when we need to clear the attachment. Without it we would need to pass color values per-component, which is inconvenient.

2024-08-29 07:30 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/vulkan/VKUtil.c
> +    Color c = {
I didn't understand about the macro. Currently the gamma correction was completely removed from code, not just conditionally disabled, so there is nothing to toggle with the macro. Or do you want me to add the macro just as an indicator?

2024-08-29 07:54 UTC, bourgesl commented on src/java.desktop/share/native/common/java2d/vulkan/VKTypes.h
> +    VkClearValue vkClearValue;
Just add comment: clearValue stores the rgba color as vulkan color...

2024-08-29 07:56 UTC, bourgesl commented on src/java.desktop/share/native/common/java2d/vulkan/VKUtil.c
> +    Color c = {
I would keep proper srgb conv here disabled by the #define flag as it is important to know.
Ideally you had somewhere else (surface?) more changes to deal properly with srgb gamma, that could be resurected and disabled by the same flag.

2024-08-29 08:04 UTC, bourgesl commented on src/java.desktop/share/native/common/java2d/vulkan/VKUtil.c
> +    Color c = {
Finally application developpers (ij platform) could mark the window to use proper srgb blending if the application is aware and supporting proper colors (opt-in), so this sRGB flag could be made dynamic => add flag/mark in the vulkan surface ?

2024-08-29 08:20 UTC, avu commented on src/java.desktop/share/native/common/java2d/vulkan/VKRenderer.c
> -void VKRenderer_TextureRender(VKDevice* device, VKImage *destImage, VKImage *srcImage,
The main purpose of this renderer was image rendering, it was used here for testing purposes and is also used in my code. So, if it's not fundamentally difficult I'd like to have it as soon as possible.

2024-08-29 08:21 UTC, avu commented on src/java.desktop/share/native/common/java2d/vulkan/VKUtil.c
> +    Color c = {
@bourgesl we discussed this topic already and decided to have a proper gamma correction as a separate feature

2024-08-29 08:29 UTC, bourgesl commented on src/java.desktop/share/native/common/java2d/vulkan/VKUtil.c
> +    Color c = {
Ok just leave bigger comment: sRGB Gamma correction remains unsupported

2024-08-29 09:11 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/vulkan/VKRenderer.c
> -void VKRenderer_TextureRender(VKDevice* device, VKImage *destImage, VKImage *srcImage,
Ok, I will bring it back with a separate commit.

2024-08-29 10:15 UTC, avu approved these changes
LGTM

2024-08-29 13:55 UTC, avu approved these changes
LGTM

2024-08-29 13:55 UTC, avu commented on src/java.desktop/share/native/common/java2d/vulkan/VKBuffer.c
> +        VKBuffer_free(device, buffer);
For consistency, we should either use capital or small letters for "methods". Currently we use capital once

2024-08-29 16:15 UTC, bourgesl approved these changes
LGTM, let's go on implementing new primitives !

2024-08-29 16:15 UTC, bourgesl commented on src/java.desktop/share/native/common/java2d/vulkan/VKRenderer.c
Looks good but vulkan API looks complicated here to insert synchronization primitives: good job !

2024-08-29 16:49 UTC, YaaZ commented on src/java.desktop/share/native/common/java2d/vulkan/VKBuffer.c
> +    VKBuffer* buffer = calloc(1, sizeof(VKBuffer));
Just re-checked: all usages of malloc are intended, we always overwrite the memory after malloc.

2024-08-29 16:52 UTC, merged