JBR-4478 Implement support for native accessible caret events on Windows
JetBrains/JetBrainsRuntime pull request #456
Opened 2024-09-03 17:47 UTC by dmitrii-drobotov

The feature adds caret tracking support for assistive tools that don't work with Java Access Bridge, specifically, for the built-in Windows Magnifier. Caret tracking will be supported on a similar level to the macOS one added in #255. Here's a quick demo: https://github.com/user-attachments/assets/9c0ef675-364c-40ba-94af-63f98e6809aa

In short, it works by implementing Win32 [IAccessible](https://learn.microsoft.com/en-us/windows/win32/api/oleacc/nn-oleacc-iaccessible) interface for the text caret and sending [EVENT_OBJECT_LOCATIONCHANGE](https://learn.microsoft.com/en-us/windows/win32/winauto/event-constants) events whenever it changes, which is very close to the way Windows system caret behaves from the accessibility side. It's also somewhat similar to the way it's implemented in [chromium](https://source.chromium.org/chromium/chromium/src/+/main:ui/accessibility/platform/ax_system_caret_win.cc), and to [`XInputMethod.ClientComponentCaretPositionTracker`](https://github.com/JetBrains/JetBrainsRuntime/blob/d99f27f3cbc29ef2a16249b6787c7d50dc09c772/src/java.desktop/unix/classes/sun/awt/X11/XInputMethod.java#L798).

For the proper Magnifier support, we would need to implement [UI Automation API](https://learn.microsoft.com/en-us/windows/win32/winauto/entry-uiauto-win32), which is a modern accessibility API on Windows. I initially started implementing it, but it turned out to be quite complex, so I decided to go with this approach of implementing IAccessible API (which is legacy, but still well supported) only for the text caret.

The feature is enabled by default and can be disabled by setting `sun.awt.windows.use.native.caret.accessibility.events` property to false.

2024-09-03 17:53 UTC, dmitrii-drobotov commented on src/java.desktop/windows/native/libawt/windows/AccessibleCaret.cpp
> +    }
Just to clarify, this is how opening and closing popups work with this workaround: https://github.com/user-attachments/assets/a99211ec-41b8-4b60-bc2f-8a675a806d09, and without: https://github.com/user-attachments/assets/b62a9c16-f6a0-4fde-a5e7-f8b1d4dc7b31.
The current behavior for popups is the way it works for JFrames and JDialogs (e.g., Find in Files dialog) even without any changes, and now will also apply to popups. But it is somewhat a regression, because this is how popups worked without this PR: https://github.com/user-attachments/assets/fe8fa24e-e13c-4461-9408-75748fc81be7, so no viewport jumping at all. This is apparently affected by the presense of an accessible object that magnifier interacted with in a window, and a proper fix would probably require implementing hierarchy (parent and child methods of IAccessible) and location of accessible objects. I think we can keep it this way for now, and maybe improve later, because I don't think it's a major problem, and can also be completely avoided by turning off keyboard focus tracking in Magnifier settings.

2024-09-11 16:31 UTC, dmitrii-drobotov commented on src/java.desktop/windows/classes/sun/awt/windows/AccessibleCaretLocationNotifier.java
> +        SwingUtilities.invokeLater(() -> {
Added `SwingUtilities.invokeLater` because we found that in some cases, components (specifically, Quick Documentation popup) could send caret updates while being in a kind of intermediate state, and accessing the text location at that moment would cause a freeze.

2024-10-05 12:30 UTC, NikitkoCent requested changes
Thank you for the patch! I have several topics to discuss

2024-10-05 12:30 UTC, NikitkoCent commented on src/java.desktop/windows/classes/sun/awt/windows/AccessibleCaretLocationNotifier.java
> +                caretNotifier = new AccessibleCaretLocationNotifier(hwnd);
Since `caretNotifier` is read and written from different threads, we should:
1. Have memory barriers around the access operations
2. Add additional check that `caretNotifier` is still `null` on the EDT

2025-04-15 14:31 UTC, dmitrii-drobotov commented on src/java.desktop/windows/native/libawt/windows/AccessibleCaret.cpp
> +    }
I decided to remove this hack for now and will create a separate issue for it. Couldn't find a way to fix it in a reasonable time, `NotifyWinEvent`s didn't help. At least there will be a workaround by disabling the keyboard focus tracking in the magnifier settings.

2025-04-15 14:40 UTC, dmitrii-drobotov commented on src/java.desktop/windows/native/libawt/windows/AccessibleCaret.h
> +    static bool isCaretUsed;
`isCaretUsed` is removed now, it was needed for the foreground window hack https://github.com/JetBrains/JetBrainsRuntime/pull/456#discussion_r1742456774.

As for m_x, m_y, m_width, m_height: as I understand, atomics wouldn't work because we need to update all four values at once, so potentially they could still be partially updated. I went with a lock by using the Win32 critical section, but I'm not sure if the best way to do it, as I'm not very familiar with the codebase. Can you confirm if it's a good way to implement a lock?

2025-04-15 14:43 UTC, dmitrii-drobotov commented on src/java.desktop/windows/native/libawt/windows/AccessibleCaret.cpp
> +    return E_NOTIMPL;
Thanks, I've updated this and other IAccessible return codes to better align with the documentation. But just to clarify, Magnifier doesn't even call most of these methods, so it's not that important.

2025-04-15 14:51 UTC, dmitrii-drobotov commented on src/java.desktop/windows/native/libawt/windows/AccessibleCaret.cpp
> +    pvarState->lVal = 0; // The state without any flags, corresponds to "normal".
The code works only for JTextComponent, and now they always have a visible caret when focused (added in https://bugs.openjdk.org/browse/JDK-4512626 for JDK 20+). For example, in the About dialog in the IDE. So I think it's fine to not implement the support for invisible state.

2025-04-15 14:58 UTC, dmitrii-drobotov commented on src/java.desktop/windows/native/libawt/windows/AccessibleCaret.cpp
> +    pvarState->lVal = 0; // The state without any flags, corresponds to "normal".
The code works only for JTextComponent-s and now they always have a visible caret when focused. It was added in https://bugs.openjdk.org/browse/JDK-4512626 for JDK 20+, and works for both JTextArea and JTextComponent. For example, in the About dialog in the IDE, or UI Sandbox - Components - JBTextField. So I think it's fine to not implement the support for invisible state.

2025-06-06 13:05 UTC, OnePatchGuy commented on src/java.desktop/windows/native/libawt/windows/AccessibleCaret.h
> +    static bool isCaretUsed;
I think a critical section is fine for `m_x`, `m_y`, `m_width`, `m_height`, but `instance` is still not guarded, although it gets read and written on different threads (EDT and the toolkit thread).

2025-06-06 13:38 UTC, OnePatchGuy commented
Have finished reviewing the recent updates. No new complaints, but one of the previous is still here

2025-06-09 10:35 UTC, dmitrii-drobotov commented on src/java.desktop/windows/native/libawt/windows/AccessibleCaret.h
> +    static bool isCaretUsed;
I've made `instance` atomic and updated usages. The only remaining issue I can think of is that, if on `WM_GETOBJECT` right after `load` but before `LResultFromObject`, the instance is released and deleted. Do you think we should protect from it? I just think it has a really small chance of happening.

2025-09-08 06:32 UTC, OnePatchGuy commented
Merged into _jbr21_ (commit `88f1599bade284e3756b1762932dac92cd639cb9`), _jbr25_ (commit `987f5f9561382befb0b512e9bcde55f7893a550e`) and _main_ branches.

2025-09-08 06:32 UTC, closed without merging