JBR-7511 migrate build platforms to OL8 for the release 2024.3
JetBrains/JetBrainsRuntime pull request #464
Opened 2024-09-23 09:20 UTC by vprovodin

2024-09-23 10:47 UTC, mkartashev requested changes

2024-09-23 10:47 UTC, mkartashev commented on jb/project/docker/Dockerfile.oraclelinux_x86_64
> +# NOTE: This Dockerfile is meant to be used from the mkdocker_aarch64.sh script.
`mkdocker_aarch64.sh` -> `mkdocker_x86_64.sh`

2024-09-23 10:47 UTC, mkartashev commented on jb/project/docker/Dockerfile.ubuntu2004_x86_64
> +# NOTE: This Dockerfile is meant to be used from the mkdocker_aarch64.sh script.
`mkdocker_aarch64.sh` -> `mkdocker_x86_64.sh`

2024-09-23 10:47 UTC, mkartashev commented on jb/project/docker/mkdocker_x86_64.sh
> +# This script creates a Docker image suitable for building AArch64 variant
`for building AArch64 variant` -> `for building the x64 variant`

2024-09-23 10:47 UTC, mkartashev commented on jb/project/docker/mkdocker_x86_64.sh
> +# of the JetBrains Runtime "dev" version.
I think the part about `"dev" version` can be dropped.

2024-09-23 10:47 UTC, mkartashev commented on jb/project/docker/mkdocker_x86_64.sh
> +docker build -t jetbrains/runtime:jbr21env_oraclelinux8_aarch64 -f Dockerfile.oraclelinux_aarch64 .
It seems to be trying to build an aarch64 version instead of x64

2024-09-23 11:02 UTC, mkartashev requested changes

2024-09-23 11:02 UTC, mkartashev commented on jb/project/docker/Dockerfile.ubuntu2004_aarch64
> +# jetbrains/runtime:jbr17env_aarch64
This name of the image is out of date

2024-09-23 11:02 UTC, mkartashev commented on jb/project/docker/Dockerfile.ubuntu2004_x86_64
> +# jetbrains/runtime:jbr17env_x86_64
This name of the image is out of date

2024-09-23 13:35 UTC, mkartashev approved these changes

2024-09-23 15:46 UTC, ujpv approved these changes

2024-09-25 07:11 UTC, avu approved these changes
LGTM

2024-09-25 07:24 UTC, YaaZ approved these changes

2024-09-27 22:28 UTC, merged