JBR-8039 Fix NPE during initalization of ZipFile through FileSystems.getDefault
JetBrains/JetBrainsRuntime pull request #485
Opened 2024-12-17 17:12 UTC by vladimirlagunov

In a case when `-Djava.nio.file.spi.DefaultFileSystemProvider` is specified and points to a class inside some JAR, this situation could happen:
* `ZipFile.<init>` tries to call `FileSystems.getDefault()`
* `FileSystems.getDefault()` calls `Class.forName()`
* `Class.forName()` calls `ZipFile.<init>`

This commit catches `NullPointerException` and switches to the original `FileSystem` in such cases.

The full stacktrace of the fixed error goes below:

```
java.lang.NullPointerException: Cannot invoke "java.nio.file.FileSystem.provider()" because the return value of "java.nio.file.FileSystems.getDefault()" is null
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1582)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1550)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:734)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:261)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:190)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:345)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.getJarFile(URLClassPath.java:809)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$1.run(URLClassPath.java:774)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$1.run(URLClassPath.java:768)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:767)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.<init>(URLClassPath.java:734)
	at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:497)
	at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:479)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
	at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:478)
	at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:446)
	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:315)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:757)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder.getDefaultProvider(FileSystems.java:124)
	at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:103)
	at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:101)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder.defaultFileSystem(FileSystems.java:101)
	at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder.<clinit>(FileSystems.java:94)
	at java.base/java.nio.file.FileSystems.getDefault(FileSystems.java:183)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1582)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1550)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:734)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:261)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:190)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:345)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.getJarFile(URLClassPath.java:809)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$1.run(URLClassPath.java:774)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$1.run(URLClassPath.java:768)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:767)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.<init>(URLClassPath.java:734)
	at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:497)
	at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:479)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
	at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:478)
	at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:446)
	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:315)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:757)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578)
	at java.base/java.lang.Class.getMethodsRecursive(Class.java:3719)
	at java.base/java.lang.Class.getMethod0(Class.java:3705)
	at java.base/java.lang.Class.getMethod(Class.java:2393)
	at java.base/jdk.internal.misc.MainMethodFinder.findMainMethod(MainMethodFinder.java:146)
	at java.base/sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:888)
	at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:726)
```

2024-12-20 09:31 UTC, mkartashev commented
This issue seems similar to https://bugs.openjdk.org/browse/JDK-8346573
I wonder if the same fix would help here as well; tentatively, it is 
```
diff --git a/src/java.base/share/classes/java/lang/System.java b/src/java.base/share/classes/java/lang/System.java
index 6ed30bacb6d..1acf18a5cf4 100644
--- a/src/java.base/share/classes/java/lang/System.java
+++ b/src/java.base/share/classes/java/lang/System.java
@@ -46,6 +46,7 @@
 import java.nio.channels.spi.SelectorProvider;
 import java.nio.charset.CharacterCodingException;
 import java.nio.charset.Charset;
+import java.nio.file.FileSystems;
 import java.security.ProtectionDomain;
 import java.util.List;
 import java.util.Locale;
@@ -1957,6 +1958,8 @@ private static void initPhase3() {
                     notSupportedJnuEncoding);
         }
 
+        FileSystems.getDefault();
+
         // initializing the system class loader
         VM.initLevel(3);
```
although we better wait for a PR from Alan Bateman.

2024-12-20 09:42 UTC, mkartashev commented
It would also be great to have a test for this situation. There are many examples in the source tree; you can use `test/jdk/java/nio/file/spi/SetDefaultProvider.java` as a template and modify it to reflect your case.

2024-12-20 09:44 UTC, mkartashev requested changes
1. Let's see if the fix for JDK-8346573 solves this one as well. In any way, catching a generic NPE is too dangerous and some other solution needs to be found.
2. Need a test for this case.

2024-12-20 17:42 UTC, vladimirlagunov commented
The suggested fix for https://bugs.openjdk.org/browse/JDK-8346573 works for me as well.

2024-12-23 14:57 UTC, mkartashev commented
Let's wait a bit for that fix to get merged upstream, then I will backport it to `jbr21` also

2024-12-23 14:57 UTC, closed without merging