JBR-8043 Fix CSE from Files.probeContentType with overridden DefaultFileSystemProvider
JetBrains/JetBrainsRuntime pull request #486
Opened 2024-12-19 11:08 UTC by vladimirlagunov

Before this commit, the code `DefaultFileTypeDetector` implied that the default file system provider is always an instance of `UnixFileSystemProvider`. It's not true when `-Djava.nio.file.spi.DefaultFileSystemProvider` is specified.

In general, there's a possibility to specify a custom `FileTypeDetector` and define it via service loading. (See `java.nio.file.Files.probeContentType`). However, the problematic code is invoked during the static initialization of the class `java.nio.file.Files.FileTypeDetectors`, which is also the entry point for the service loader. This way, it's even impossible to define a custom `FileTypeDetector`.

This commit replaces the strict class cast with a conditional one, and the new code returns a no-op file type detector in cases when the default file system provider is overridden.

2024-12-20 10:10 UTC, mkartashev requested changes

2024-12-20 10:10 UTC, mkartashev commented on src/java.base/unix/classes/sun/nio/fs/DefaultFileTypeDetector.java
> +        if (provider instanceof UnixFileSystemProvider) {
You can avoid casting on the next line if you bind the instance to a variable like so
```
if (provider instanceof UnixFileSystemProvider unixProvider) {
   return unixProvider.getFileTypeDetector();
}
```

2024-12-20 12:44 UTC, vladimirlagunov commented on src/java.base/unix/classes/sun/nio/fs/DefaultFileTypeDetector.java
> +        if (provider instanceof UnixFileSystemProvider) {
https://github.com/JetBrains/JetBrainsRuntime/pull/486/commits/18cb31b8b75dce871926cba72d9e4c66809315a1

2024-12-23 11:22 UTC, mkartashev approved these changes
Looks good. I will add a dedicated test, run the existing tests, and merge this manually (first into `main` and then into `jbr21`).

2024-12-24 06:34 UTC, mkartashev commented
Merged into `main` and `jbr21` ([fd29e06c9c](https://github.com/JetBrains/JetBrainsRuntime/commit/fd29e06c9c098322fd0e7ae2a4e8d5ae46564c0e)).

2024-12-24 06:34 UTC, closed without merging